### ISSUE TITLE
引入生成就报错

### ISSUE THREAD

**Issue by diuxiezi** [rongcloud/rongcloud-im-flutter-sdk#10]
引入后就生成就开始报错：
    D8: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver
    FAILURE: Build failed with an exception.

Flutter 版本 1.7
rongcloud_im_plugin 0.9.2

**Comment by loginSin** [comment]
直接使用源码中的 Android 项目会报错吗？看样子像是 Android 项目配置的问题

**Comment by dukezhao** [comment]
same question
