### ISSUE TITLE
最新版本和老flutter有不兼容的地方

### ISSUE THREAD

**Issue by AliceCheney** [rongcloud/rongcloud-im-flutter-sdk#103]
我的版本1.7.8+hotfix4 插件版本1.1.1 启动就会报:找不到import androidx.annotation.StringRes;

**Comment by zoulu123** [comment]
您尝试打开本地缓存的库，并找到 StorageUtils 中把相应代码删除掉，这边已经没有使用过这个包，可能迁移升级中导致找不到
