### ISSUE TITLE
运行SDK的例子，一点APP就闪退，

### ISSUE THREAD

**Issue by DriverFrameWork** [rongcloud/rongcloud-im-flutter-sdk#104]
运行SDK的例子，一点APP就闪退,也没有输出内容，
redmi 7

**Comment by zoulu123** [comment]
请您按照如下步骤收集一下异常情况下的日志
先清理一下手机缓存，使用指令 adb logcat -> 1.txt

**Comment by DontDream1** [comment]
你成功了吗，我现在也是闪退 同 红米 k30

**Comment by jz8912** [comment]
一打开例子的app闪退是个什么问题哦

**Comment by ios-yifan** [comment]
您好，请问现在还有遇到此问题吗？可以使用最新版本的 demo 测试一下。

**Comment by ios-yifan** [comment]
您好，当前问题即将关闭，后续使用遇到任何问题可以在融云开发者后台提交工单，会有我们的技术人员进行及时处理。
