### ISSUE TITLE
消息的model类为何没有发送者的昵称和头像

### ISSUE THREAD

**Issue by mengsiyitiaojie** [rongcloud/rongcloud-im-flutter-sdk#105]
是不是需要自己手动在model类中添加发送者的昵称和头像

**Comment by CNHarrySun** [comment]
您可以通过 Message 的 senderUserId 从 App 层获取到用户的昵称和头像或者在发消息时将 MessageContent（TextMessage、ImageMessage 等消息） 的 sendUserInfo 赋值，展示的时候使用 sendUserInfo。

发送消息携带用户信息参考：https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/doc/%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF%E6%90%BA%E5%B8%A6%E7%94%A8%E6%88%B7%E4%BF%A1%E6%81%AF.md
