### ISSUE TITLE
Flutter Android demo无法运行

### ISSUE THREAD

**Issue by IOCloudFly** [rongcloud/rongcloud-im-flutter-sdk#106]
* 本地 Flutter 1.12,Dart版本是2.7
* 异常设备是 Android，华为荣耀8x,SDK 版本 29
* 我是运行github上 example 下的Android 项目，grdle什么都一致，也是Anroidx
* 错误: 找不到符号
符号:   类 ActivityCompat
位置: 程序包 android.support.v4.app

<img width="1242" alt="rong1@2x" src="https://user-images.githubusercontent.com/45480314/81461435-53a04100-91de-11ea-9050-15eebbde7185.png">

**Comment by IOCloudFly** [comment]
<img width="1352" alt="rong2@2x" src="https://user-images.githubusercontent.com/45480314/81461471-a4179e80-91de-11ea-97a6-030e4b791b2f.png">

**Comment by IOCloudFly** [comment]
flutter_sonud 插件，不知道啥原因

**Comment by IOCloudFly** [comment]
已解决
应该AndroidX的原因。
把Flutter_sound插件里面的
import android.support.v4.app.ActivityCompat;
改成
import androidx.core.app.ActivityCompat;

**Comment by zoulu123** [comment]
好的
