### ISSUE TITLE
RongcloudImPlugin.sendMessageWithCallBack 在Android端无法回调

### ISSUE THREAD

**Issue by chu69263** [rongcloud/rongcloud-im-flutter-sdk#107]
* Flutter 1.17.0 • channel stable
* rongcloud_im_plugin: ^1.1.1
RongcloudImPlugin.sendMessageWithCallBack 在Android端无法回调,在ios正常
查看源码好像是Android回调没有返回timestamp key，导致flutter找不到回调方法

**Comment by CNHarrySun** [comment]
OK，感谢反馈，我们添加下 Android 这块的逻辑。

**Comment by CNHarrySun** [comment]
问题已于 2.0.0 版本修复
