### ISSUE TITLE
listview 设置reverse为true后 会导致向数组加入数据，更新视图后直接到底部 而不是刷新时的位置

### ISSUE THREAD

**Issue by liubaishui** [rongcloud/rongcloud-im-flutter-sdk#108]
询问作者什么时间能够更新插件 ，及问问作者大佬，如何实现下拉加载而不会导致直接跳转到第一条呢？就是listview 设置reverse为true后 会导致向数组加入数据，更新视图后直接到底部 而不是刷新时的位置

_Originally posted by @speanut-land in https://github.com/rongcloud/rongcloud-im-flutter-sdk/issues/31#issuecomment-534438980_

**Comment by CNHarrySun** [comment]
记录 scrollController.position.pixels，然后更新的时候 this._scrollController = ScrollController(initialScrollOffset: mPosition); 试下

**Comment by liubaishui** [comment]
https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/79b281891cc068176e3da2be957aceeb2784ce17/example/lib/im/pages/item/message_content_list.dart#L169

我看了example中就是这么做的，我也是这么干的，可是还是会刷新到底部去。 并没有预想中的效果

**Comment by ios-yifan** [comment]
您好，可以参考一下最新版本的 demo。

**Comment by ios-yifan** [comment]
您好，当前问题即将关闭，后续使用遇到任何问题可以在融云开发者后台提交工单，会有我们的技术人员进行及时处理。
