### ISSUE TITLE
iOS引入出错

### ISSUE THREAD

**Issue by 0xBinX** [rongcloud/rongcloud-im-flutter-sdk#11]
0.9.2版本
=== BUILD TARGET url_launcher OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/++++/fluttersdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/rongcloud_im_plugin-0.9.2/ios/Classes/RCIMFlutterWrapper.m:186:25: warning: unused variable 'user' [-Wunused-variable]
                RCUserInfo *user = [[RCUserInfo alloc] initWithUserId:userId name:name portrait:portraitUrl];
                            ^
    /Users/++++/fluttersdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/rongcloud_im_plugin-0.9.2/ios/Classes/RCIMFlutterWrapper.m:261:20: error: unknown receiver 'RCHQVoiceMessage'; did you mean 'RCVoiceMessage'?
            content = [RCHQVoiceMessage messageWithPath:localPath duration:duration];
                       ^~~~~~~~~~~~~~~~
                       RCVoiceMessage
    In module 'RongIMLib' imported from /Users/++++/fluttersdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/rongcloud_im_plugin-0.9.2/ios/Classes/RCFlutterMessageFactory.h:9:
    /Users/++++/workspace/++++/ios/Pods/RongCloudIM/RongCloudIM/RongIMLib.framework/Headers/RCVoiceMessage.h:25:12: note: 'RCVoiceMessage' declared here
    @interface RCVoiceMessage : RCMessageContent <NSCoding>
               ^
    /Users/++++/fluttersdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/rongcloud_im_plugin-0.9.2/ios/Classes/RCIMFlutterWrapper.m:261:37: error: no known class method for selector 'messageWithPath:duration:'
            content = [RCHQVoiceMessage messageWithPath:localPath duration:duration];
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning and 2 errors generated.

**Comment by loginSin** [comment]
看样子是iOS SDK IMLib 的版本过低，
1.在  Podfile 目录执行以下 pod repo update ，更新 pod 本地仓库
2.执行 pod update 安装新版本的 iOS SDK
然后再看一下效果

**Comment by loginSin** [comment]
应该 iOS IMLib 版本至少得是 2.9.19

**Comment by 0xBinX** [comment]
按照你说的方法，成功解决这个问题 @loginSin 
但是又出现新的问题：init的时候错误码-1000
这应该是开发者接口调用时传入的参数错误。请检查接口调用时传入的参数类型和值。

我的android上是正常的

**Comment by loginSin** [comment]
其提供必要的 log，只有这些没办法准确定位问题
