### ISSUE TITLE
connect连接报错

### ISSUE THREAD

**Issue by leielyq** [rongcloud/rongcloud-im-flutter-sdk#110]
像实现一下发送状态监听的，所以更新到2.0.0.
但是connect()方法报错了

await _channel.invokeMethod(RCMethodKey.Connect, token)  Android设备上这个方法返回的int类型的值。但是sdk里面用map去接收，出现了类型转换异常。

**Comment by CNHarrySun** [comment]
正在修复这个问题~

**Comment by CNHarrySun** [comment]
该问题已经修复，更新至 2.0.0+1 即可。
