### ISSUE TITLE
flutter run -- release 报错

### ISSUE THREAD

**Issue by zhangyc** [rongcloud/rongcloud-im-flutter-sdk#111]
flutter版本1.17
错误日志：
* What went wrong:                                                      
Could not determine the dependencies of task ':app:lintVitalRelease'.   
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not resolve cn.rongcloud.sdk:im_lib:2.10.6.                  
     Required by:                                                       
         project :app > io.rong.flutter.imlib:rongcloud_im_plugin_release:1.0
      > Skipped due to earlier error                                    
      > Skipped due to earlier error                                    
      > Skipped due to earlier error                                    
                                                                        
* Try:                                                                  
Run with

**Comment by CNHarrySun** [comment]
你更换下网络试下，可能是 Maven 没有拉下来。
