### ISSUE TITLE
RC:VcMsg 这个消息格式怎样接收？

### ISSUE THREAD

**Issue by yingqiang006** [rongcloud/rongcloud-im-flutter-sdk#114]
我这边拿到的语音消息，content为null，只能拿到时长字段，没有音频路径

**Comment by CNHarrySun** [comment]
你好，目前 SDK 中使用的是高清语音消息（"RC:HQVCMsg"），RC:VcMsg 是普通语音消息，需要通过下面方法获取：

由于 Flutter 目前不支持反射，所以自定义的消息无法被正常解码，自定义消息的数据会被放在 Flutter Message 和 Conversation 对象的 originContentMap 中

**Comment by abina2020** [comment]
你好，请问当前的版本有群聊功能吗？

**Comment by yingqiang006** [comment]
有啊，我已经切到2.0.0了。
originContentMap 这个字段里只有三个key，没有语音的url，也没有base64串，我怎么才能读取这条语音那？

**Comment by CNHarrySun** [comment]
您在 rong_im_client.dart 的 _addNativeMethodCallHandler 方法的 case RCMethodCallBackKey.ReceiveMessage: 中打个断点，看下 iOS 或者 Android 返回给 Flutter 的 map 是什么内容。
