### ISSUE TITLE
setMessageSentStatus 这个接口如何使用啊

### ISSUE THREAD

**Issue by leielyq** [rongcloud/rongcloud-im-flutter-sdk#115]
好像只有发送成功之后才会有messageId啊，那都发送成功了，就不用监听发送状态啊。
我想要做 用户点击发送之后  页面就会显示发送的内容 然后有个小圈圈表示正在发送。最后根据异步回调显示发送成功还是失败。

**Comment by CNHarrySun** [comment]
数据库插入消息时就会有 messageId，你可以调用发送消息时展示正在发送的控件，通过发送消息的  callback 或者 onMessageSend 中判断发送成功后再将正在发送的控件隐藏。

通过 sendMessage
