### ISSUE TITLE
你好，请问当前的版本有群聊功能吗？

### ISSUE THREAD

**Issue by yingqiang006** [rongcloud/rongcloud-im-flutter-sdk#116]
你好，请问当前的版本有群聊功能吗？

_Originally posted by @abina2020 in https://github.com/rongcloud/rongcloud-im-flutter-sdk/issues/114#issuecomment-638079080_

**Comment by CNHarrySun** [comment]
![image](https://user-images.githubusercontent.com/16249166/84460920-c00ad600-ac9d-11ea-9da5-885facee564a.png)
会话列表中设置显示 group 的会话
