### ISSUE TITLE
sendMessageWithCallBack问题

### ISSUE THREAD

**Issue by leielyq** [rongcloud/rongcloud-im-flutter-sdk#118]
sendMessageWithCallBack 该方法发送消息之后 RongIMClient.onMessageSend 依然会接收到回调

**Comment by CNHarrySun** [comment]
消息插入到本地数据库时没有将 timestamp 传回到 flutter 层，所以此时走一次 onMessageSend，消息真正发送成功时会走对应的 callback。

**Comment by leielyq** [comment]
/// 发送消息之后有两种查看结果的方式：1、发送消息的 callback 2、onMessageSend；推荐使用 callback 的方式
  /// 如果未实现此方法的 callback，则会通过 onMessageSend 返回发送消息的结果

那这里注释会让人无解 走callback就不会走onMessageSend了吧
