### ISSUE TITLE
不能撤回和转发自定义消息

### ISSUE THREAD

**Issue by leielyq** [rongcloud/rongcloud-im-flutter-sdk#119]
控制台打印  recallMessage message content is nil。
但是按照常理，自定义消息只有originMap

**Comment by CNHarrySun** [comment]
这个在 recallMessage 时会被拦截取不到 content 的情况
![image](https://user-images.githubusercontent.com/16249166/84459121-3d801780-ac99-11ea-9045-69df1d2ef2e1.png)
