### ISSUE TITLE
点击获取聊天列表失败

### ISSUE THREAD

**Issue by zhaolixiang** [rongcloud/rongcloud-im-flutter-sdk#12]
'''
I/[RC-Flutter-IM] Android (13045): getConversationList start 
D/[RC:P-reason-C](13045): {"ptid":"13116-2003","action":"conv_list","reason":"db not open"}
I/[RC-Flutter-IM] Android (13045): getConversationList success 
E/flutter (13045): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'iterator' was called on null.
E/flutter (13045): Receiver: null
E/flutter (13045): Tried calling: iterator
E/flutter (13045): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
'''

**Comment by zhaolixiang** [comment]
还有，是不是聊天列表页面是不是得自己写。。。

**Comment by loginSin** [comment]
关于 1 楼的问题是因为数据库没有打开："reason":"db not open"，可能的原因是 IM 尚未连接成功就获取回话列表，所以导致了失败，具体的错误需要详细的 log
关于 2 楼的问题，我们现在正在开发基于 Flutter 会话列表和聊天页面，详情可以参见该仓库的 dev 分支，不过现在还有不完善的地方
