### ISSUE TITLE
getConversationList()可以返回notificationStatus字段吗

### ISSUE THREAD

**Issue by chu69263** [rongcloud/rongcloud-im-flutter-sdk#122]
rongcloud_im_plugin: ^1.1.1

Android中Conversation类有notificationStatus字段
```
public class Conversation implements Parcelable {
 ...
 private Conversation.ConversationNotificationStatus notificationStatus;
 ...
}
```
但是flutter中Conversation类没有这个字段；

可否返回这个字段，这样会话列表就不需要每个item都要调用getConversationNotificationStatus获取了

**Comment by CNHarrySun** [comment]
可以的，这个后面优化 flutter 中 Conversation 的字段

**Comment by aliyoge** [comment]
> 可以的，这个后面优化 flutter 中 Conversation 的字段

请问什么时候实现，现在还没有。

**Comment by CNHarrySun** [comment]
已添加，正在测试中。
