### ISSUE TITLE
RongIMClient.searchConversations方法疑问

### ISSUE THREAD

**Issue by leielyq** [rongcloud/rongcloud-im-flutter-sdk#123]
有个key的参数，如果是图片就没有key了。
还有可以提供一个获取特定的消息类型但是不指定targetId的方法吗？有个需求我需要拿到所有的自定消息。
本来以为RongIMClient.searchConversations这个方法可以获取到特定的消息类型，可是拿不到。
sad

**Comment by leielyq** [comment]
要不组织一个qq群吧

**Comment by CNHarrySun** [comment]
![image](https://user-images.githubusercontent.com/16249166/84985624-ab33b400-b16f-11ea-96d1-1b6bfd7aa728.png)
目前 SDK 中只有这一个搜索会话的方法，自定义的消息实现 RCMessageContent 的 getSearchableWords 接口在进行搜索试下。

**Comment by leielyq** [comment]
好吧  可以加上这样的功能吗

**Comment by CNHarrySun** [comment]
接口这个会加到 iOS 和 Android SDK 的需求池中
