### ISSUE TITLE
RongIMClient.sendMessageWithCallBack  同时多次调用

### ISSUE THREAD

**Issue by leielyq** [rongcloud/rongcloud-im-flutter-sdk#124]
RongIMClient.sendMessageWithCallBack 多次调用的时候  callback回调次数不对。
多图同时发送的场景

**Comment by CNHarrySun** [comment]
出现这个问题使用的 版本以及设备是什么？

**Comment by leielyq** [comment]
@CNHarrySun android  v2.0.0+1

**Comment by zoulu123** [comment]
请问您的回调次数不对具体是什么不对，回调结果多次还是？使用的是 android 设备还是 ios
