### ISSUE TITLE
有没有交流群什么的  文档不是很详细  dome跑起来闪退  没办法参考

### ISSUE THREAD

**Issue by jijkbird** [rongcloud/rongcloud-im-flutter-sdk#125]
有没有交流群什么的  文档不是很详细  dome跑起来闪退  没办法参考

**Comment by CNHarrySun** [comment]
暂时没有交流群，请问闪退报错是什么？

**Comment by jijkbird** [comment]
> 暂时没有交流群，请问闪退报错是什么？

真机打开就没了  没有任何弹窗
模拟器显示已停止运行

控制台无法打印任何信息

**Comment by DontDream1** [comment]
红米k30 demo秒闪退   没有任何错误信息

**Comment by jz8912** [comment]
闪退的是啥问题嘛，运行环境如下：
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 1.17.5 at D:\flutter_windows_1.17.5-stable\flutter
    • Framework revision 8af6b2f038 (3 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at D:\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Note9     • 923QEDUM226JB    • android-arm64 • Android 9 (API 28)
    • PLK TL01H • K4P0215829004987 • android-arm64 • Android 6.0 (API 23)

• No issues found!

**Comment by ios-yifan** [comment]
您好，当前还有遇到此问题吗? 可以使用最新版的 demo 测试一下。

**Comment by ios-yifan** [comment]
您好，当前问题即将关闭，后续使用遇到任何问题可以在融云开发者后台提交工单，会有我们的技术人员进行及时处理。
