### ISSUE TITLE
RongIMClient.getConversationList方法中没有发送者信息

### ISSUE THREAD

**Issue by jijkbird** [rongcloud/rongcloud-im-flutter-sdk#127]
latestMessageContent.userinfo为空

**Comment by CNHarrySun** [comment]
你好，是不是在发送消息的时候没有携带用户信息。
![image](https://user-images.githubusercontent.com/16249166/87142159-ba250680-c2d6-11ea-991f-3e35747e7006.png)

**Comment by ToZhanChi** [comment]
我是通过官网api发送消息并勾选了发送用户信息，客户端接收也是没有userinfo

**Comment by CNHarrySun** [comment]
![image](https://user-images.githubusercontent.com/16249166/89623229-d3fe3d00-d8c6-11ea-9154-024145becb97.png)

可以在接收消息的方法里打个断点看下 Native 层返回的数据是否携带了发送者信息。

![image](https://user-images.githubusercontent.com/16249166/89623270-e7110d00-d8c6-11ea-8d6e-339407fe17db.png)

获取会话列表时在这里打个断点看下。
