### ISSUE TITLE
ios 报错 No visible @interface for 'RCIMClient' declares the selector 'connectWithToken:success:error:tokenIncorrect:'

### ISSUE THREAD

**Issue by NiBoTe** [rongcloud/rongcloud-im-flutter-sdk#129]
No visible @interface for 'RCIMClient' declares the selector 'connectWithToken:success:error:tokenIncorrect:'

**Comment by 1xiaocainiao** [comment]
How to solve the same problem

**Comment by CNHarrySun** [comment]
命令行中执行 pod repo update 更新本地 pod，然后 Flutter 集成时指定 2.1.0 版本，2.1.0 版本是适配 RongCloudI M SDK 4.0.0 的。
![image](https://user-images.githubusercontent.com/16249166/85939636-bf369d00-b949-11ea-8d1f-4ebf2461ca1e.png)

**Comment by 1xiaocainiao** [comment]
> 命令行中执行 pod repo update 更新本地 pod，然后 Flutter 集成时指定 2.1.0 版本，2.1.0 版本是适配 RongCloudI M SDK 4.0.0 的。
> ![image](https://user-images.githubusercontent.com/16249166/85939636-bf369d00-b949-11ea-8d1f-4ebf2461ca1e.png)

感谢解答
