### ISSUE TITLE
java Long 转 Integer 出错的问题

### ISSUE THREAD

**Issue by wukailu** [rongcloud/rongcloud-im-flutter-sdk#13]
小bug一个， 
rongcloud-im-flutter-sdk/android/src/main/java/com/example/rongcloud_im_plugin/RCIMFlutterWrapper.java:746

Integer sendTime = (Integer)map.get("sendTime");

应该改为

Long sendTime = (Long)map.get("sendTime");

不然调用insertOutgoingMessage会GG

**Comment by wukailu** [comment]
抱歉，行数说错了，是809行

**Comment by loginSin** [comment]
你好，这边查了一下代码，809 行确实是用的 Integer 接收的 sendTime 但是在 838 行用到的时候会将其转为 long ,可以参见此链接
https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/android/src/main/java/com/example/rongcloud_im_plugin/RCIMFlutterWrapper.java#L838
如果是本地的代码出现了这个问题，建议升级一下版本，当前最新版本为  0.9.3 参见 https://pub.dev/packages/rongcloud_im_plugin

**Comment by wukailu** [comment]
这里出错是 Integer sendTime = (Integer)map.get("sendTime");中map.get("sendTime")返回的是Long类型，会在这一行转换的时候出错

**Comment by loginSin** [comment]
明白你的意思了，有可能 Android 里面所有对 Flutter 传过来时间戳的处理都有问题，明天我会整体过一遍

**Comment by loginSin** [comment]
问题已解决，最新版本 0.9.4

**Comment by wukailu** [comment]
谢谢
