### ISSUE TITLE
2.1.0的 RCIMFlutterWrapper.m 文件有点问题

### ISSUE THREAD

**Issue by TheLiyo** [rongcloud/rongcloud-im-flutter-sdk#130]
line296,
//        [[RCIMClient sharedRCIMClient] connectWithToken:token dbOpened:^(RCDBErrorCode code) {
//
//        } success:^(NSString *userId) {
//
//        } error:^(RCConnectErrorCode errorCode) {
//
//        }];
这里没有替换成新方法

**Comment by CNHarrySun** [comment]
请问是什么问题？
2.1.0 是适配了 IM SDK 4.0.0 版本修改了 connect 接口。
https://docs.rongcloud.cn/v3/views/im/ui/guide/private/connection/connect/ios4.html

**Comment by TheLiyo** [comment]
2.1.0版本RCIMFlutterWrapper.m中的connect接口还是调用的旧方法，运行时会因为找不到方法报错。demo应该是跑不通的吧。
这个方法： [[RCIMClient sharedRCIMClient] connectWithToken:@"" dbOpened:^(RCDBErrorCode code) {} success:^(NSString *userId) {} error:^(RCConnectErrorCode errorCode) {}];是不是该替换成这个：
[[RCIMClient sharedRCIMClient] connectWithToken:@"" dbOpened:^(RCDBErrorCode code) {} success:^(NSString *userId) { } error:^(RCConnectErrorCode status) {} tokenIncorrect:^{ }];

**Comment by CNHarrySun** [comment]
你升级到最新的版本试下。
目前使用的方法：
![image](https://user-images.githubusercontent.com/16249166/87140581-54d01600-c2d4-11ea-92d0-ca84d082eb53.png)
