### ISSUE TITLE
位置消息解析是不是有问题

### ISSUE THREAD

**Issue by leielyq** [rongcloud/rongcloud-im-flutter-sdk#131]
源码是这样的：

@override
  void decode(String jsonStr) {
    if (jsonStr == null && jsonStr.isEmpty) {
      developer.log("Flutter LocationMessage deocde error: no content",
          name: "RongIMClient.LocationMessage");
      return;
    }
    Map map = json.decode(jsonStr);
    this.mLat = map["latitude"];
    this.mLng = map["longitude"];
    this.mPoi = map["poi"];
    this.mBase64 = map["content"];
    this.mImgUri = map["content"];
    Map userMap = map["user"];
    super.decodeUserInfo(userMap);
  }

    this.mBase64 = map["content"];
    this.mImgUri = map["content"];  一直拿不到mImgUri

**Comment by leielyq** [comment]
但是我debug看了一下上面方法的参数，jsonStr ： {"latitude":37.30687667342615,"longitude":-121.97310827672483,"poi":"1060 Ranchero Way, San Jose, CA 95117, USA","isBurnAfterRead":false,"burnDuration":0}，也没有img啊，这就不懂了

**Comment by leielyq** [comment]
android  2.1.0

**Comment by zoulu123** [comment]
你发送位置消息的时候应该自己在内部赋予这个远端地址，类似 http 的地址， sdk 是高德地图直接返回的

**Comment by leielyq** [comment]
@zoulu123  你好，我已经构建了LocationMessage msg = LocationMessage.obtain(bean.latitude,bean.longitude, bean.name, AppMapKits.getMapImage(bean));但是就是没有呀

**Comment by leielyq** [comment]
@CNHarrySun LocationMessage这个类源码真的有问题呀

**Comment by CNHarrySun** [comment]
你好，请问对这个类有什么疑问呢？

**Comment by leielyq** [comment]
**
this.mBase64 = map["content"];
this.mImgUri = map["content"];
**

这个代码是正确的？

**Comment by 1xiaocainiao** [comment]
楼主你好，请问你实现发送地理位置了吗，用的什么地图插件呢
