### ISSUE TITLE
三方推送问题

### ISSUE THREAD

**Issue by ToZhanChi** [rongcloud/rongcloud-im-flutter-sdk#132]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
* 异常设备是 iOS 还是 Android，列出具体机型和系统
* 所调用的是什么 API 或者说是什么功能
* 完整的报错信息或者问题描述
* 提供问题发生时必要的日志，并以 txt 形式上传

文档链接 https://github.com/rongcloud/rongcloud-im-flutter-sdk/tree/dev/doc
文档持续更新中……

Flutter 有没有集成三方推送？文档中提到到Andoroid IOS原生推送集成，flutter没有详细文档

**Comment by CNHarrySun** [comment]
本地通知和远程推送的实现：https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/doc/%E6%9C%AC%E5%9C%B0%E9%80%9A%E7%9F%A5%E4%B8%8E%E8%BF%9C%E7%A8%8B%E6%8E%A8%E9%80%81%E7%9A%84%E5%AE%9E%E7%8E%B0.md

**Comment by CNHarrySun** [comment]
原生推送集成：
https://docs.rongcloud.cn/v3/views/im/noui/guide/private/notify/push/ios.html
https://docs.rongcloud.cn/v3/views/im/noui/guide/private/notify/push/rong.html

**Comment by DDstar** [comment]
> 原生推送集成：
> https://docs.rongcloud.cn/v3/views/im/noui/guide/private/notify/push/ios.html
> https://docs.rongcloud.cn/v3/views/im/noui/guide/private/notify/push/rong.html



> 原生推送集成：
> https://docs.rongcloud.cn/v3/views/im/noui/guide/private/notify/push/ios.html
> https://docs.rongcloud.cn/v3/views/im/noui/guide/private/notify/push/rong.html

您的意思是使用推送的话还要自己写原生的ios和安卓代码吗

**Comment by CNHarrySun** [comment]
是的，得在原生层处理
