### ISSUE TITLE
调用connect的时候报错

### ISSUE THREAD

**Issue by jiangchunyun** [rongcloud/rongcloud-im-flutter-sdk#134]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
* android
* connect
* E/[RC:L-reconnect-R][IM]( 9919): {"ptid":"9919-116681","code":"IPC_DISCONNECT","network":"WIFI","sequences":0}
* 提供问题发生时必要的日志，并以 txt 形式上传

文档链接 https://github.com/rongcloud/rongcloud-im-flutter-sdk/tree/dev/doc
文档持续更新中……

**Comment by zoulu123** [comment]
你这边是只调取 connect 就触发的异常嘛，请问能提供下更加详细的日志吗？
