### ISSUE TITLE
Could not get resource

### ISSUE THREAD

**Issue by zichenfang** [rongcloud/rongcloud-im-flutter-sdk#135]
Android studio 运行安卓手机，提示
* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not download im_lib.aar (cn.rongcloud.sdk:im_lib:4.0.0.2)
      > Could not get resource 'https://dl.bintray.com/rongcloud/maven/cn/rongcloud/sdk/im_lib/4.0.0.2/im_lib-4.0.0.2.aar'.
其他插件正常使用，就融云不行

**Comment by CNHarrySun** [comment]
这个问题像是 maven 没有拉下来，你切换网络重新试下。

**Comment by haoXu1990** [comment]
@zichenfang  请问你最后怎么解决的，我 maven 设置了代理，其它都能正常，就融云的插件提示403
