### ISSUE TITLE
融云flutter版没有UI吗？

### ISSUE THREAD

**Issue by Meditator-K** [rongcloud/rongcloud-im-flutter-sdk#136]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
* 异常设备是 iOS 还是 Android，列出具体机型和系统
* 所调用的是什么 API 或者说是什么功能
* 完整的报错信息或者问题描述
* 提供问题发生时必要的日志，并以 txt 形式上传

文档链接 https://github.com/rongcloud/rongcloud-im-flutter-sdk/tree/dev/doc
文档持续更新中……

**Comment by CNHarrySun** [comment]
你好，是的，rongcloud_im_plugin 是基于 IMLib 开发的，你可以运行 rongcloud-im-flutter-sdk/example 中的项目看下效果。

**Comment by Meditator-K** [comment]
嗯，看了，发现个bug，在会话界面，下拉刷新拉取历史消息的时候，刚划到头列表就立马跳转到最下方显示最新消息了，而不是停留在上方历史消息位置

**Comment by CNHarrySun** [comment]
这个问题是没有更新 position，我们后期会排期优化下。

**Comment by learyR** [comment]
> 这个问题是没有更新 position，我们后期会排期优化下。

请问这个问题 有没有解决方案呢，着急使用

**Comment by Leon-ele** [comment]
> > 这个问题是没有更新 position，我们后期会排期优化下。
> 
> 请问这个问题 有没有解决方案呢，着急使用

listView 每次build时 重新初始化 scrollController 的 postion 为上次的 mpositon 就可以了

**Comment by learyR** [comment]
> > > 这个问题是没有更新 position，我们后期会排期优化下。
> > 
> > 
> > 请问这个问题 有没有解决方案呢，着急使用
> 
> listView 每次build时 重新初始化 scrollController 的 postion 为上次的 mpositon 就可以了

问题我已经解决了，是那个uniqueKey的问题。每次都是新的ListView。还是谢谢回复
