### ISSUE TITLE
会话列表中getConversationList返回数据总会多一个id是RongRTC

### ISSUE THREAD

**Issue by Meditator-K** [rongcloud/rongcloud-im-flutter-sdk#138]
你好，我这边在flutter版demo的基础上做了些修改，好友列表是我们服务器返回的，刚登陆时会话列表是空白，但是在好友列表和会话列表两个tab之间来回切换几次，就发现通过getConversationList获取会话列表时返回数据总会多一个id是RongRTC的用户，但是我的好友列表中都没有这个好友，代码中全局搜索也没有RongRTC字样，麻烦看一下，谢谢！
[融云flutter版日志.txt](https://github.com/rongcloud/rongcloud-im-flutter-sdk/files/4900769/flutter.txt)

**Comment by CNHarrySun** [comment]
你好，请问能知道具体从哪个方法调用到 RongIMClient.MessageFactory 吗？在 contacts_page 中有 RongRTC 相关的代码。

你现在 getConversationList 方法中打个日志，看下从 Native 层获取到的数据是否包含 RongRTC 会话。

**Comment by Meditator-K** [comment]
contacts_page中RongRTC相关代码我已经删掉了，现在好友列表是通过我们服务器获取的，从日志中看服务器数据也没有RongRTC这个id的。我是在conversation_list_page.dart中调用的RongIMClient.getConversationList方法获取会话列表的，这个是demo中的代码，我没改动，RongIMClient.MessageFactory这个日志应该是getConversationList方法中你们框架打印的。现在比较头疼的就是，代码中完全没有RongRTC字样，这个id不知道哪来的，getConversationList是完全从本地读取会话记录还是会请求服务器呀？getConversationList是你们框架的，我没法打日志呀~，从上面的TXT日志文件中能看出什么吗？

**Comment by Meditator-K** [comment]
请忽略吧，今天重新打包自己好了。。。
