### ISSUE TITLE
IOS启动报错

### ISSUE THREAD

**Issue by herghost000** [rongcloud/rongcloud-im-flutter-sdk#14]
Error output from CocoaPods:
↳
         % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                        Dload  Upload   Total   Spent    Left  Speed
     0 69.9M    0  549k    0     0    972      0 20:58:27  0:09:38 20:48:49     0
       curl: (56) Recv failure: Operation timed out

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

    [!] 'RongCloudIM' uses the unencrypted 'http' protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts. Otherwise, please reach out to the library author to notify them of this security issue.

Error running pod install
Error launching application on iPhone Xʀ.

**Comment by loginSin** [comment]
看样子是 iOS pod 下载 SDK 出现了问题
1.在 Podfile 目录执行以下 pod repo update ，更新 pod 本地仓库
2.执行 pod update 安装新版本的 iOS SDK
然后再看一下效果

**Comment by herghost000** [comment]
> 看样子是 iOS pod 下载 SDK 出现了问题
> 1.在 Podfile 目录执行以下 pod repo update ，更新 pod 本地仓库
> 2.执行 pod update 安装新版本的 iOS SDK
> 然后再看一下效果

我按你的步骤执行后：

Operation timed out 这个错误消失了

但是

Error running pod install
Error launching application on iPhone Xʀ.
这个错误依旧存在，😭

**Comment by herghost000** [comment]
解决了，是pod太慢的问题。

> > 看样子是 iOS pod 下载 SDK 出现了问题
> > 1.在 Podfile 目录执行以下 pod repo update ，更新 pod 本地仓库
> > 2.执行 pod update 安装新版本的 iOS SDK
> > 然后再看一下效果
> 
> 我按你的步骤执行后：
> 
> Operation timed out 这个错误消失了
> 
> 但是
> 
> Error running pod install
> Error launching application on iPhone Xʀ.
> 这个错误依旧存在，😭

解决了，是pod太慢的问题
