### ISSUE TITLE
4.0.1+1版本中 取默认的历史消息为空数组  

### ISSUE THREAD

**Issue by mengsiyitiaojie** [rongcloud/rongcloud-im-flutter-sdk#140]
连接状态为34001  刚发送的消息未离开聊天界面有获取到消息  但是一旦离开聊天页面再进入聊天消界面的时候就获取的是空数组了

**Comment by mengsiyitiaojie** [comment]
![image](https://user-images.githubusercontent.com/55568326/88253281-f186b080-cce3-11ea-8248-23af5b941434.png)

**Comment by CNHarrySun** [comment]
您好，34001 是因为连接已经存在，多次调用 connect 导致，您可以通过 disconnect 然后再 connect；
获取历史消息时传入的参数是否正确。
