### ISSUE TITLE
4.0.1+1版本demo发送消息后,聊天界面会显示2条重复消息

### ISSUE THREAD

**Issue by zengshan233** [rongcloud/rongcloud-im-flutter-sdk#141]
个人在项目中将sdk从2.1.1升级到4.0.1+1后发现的问题，并在demo中验证均存在，消息发送后立即返回的Message其messageId为0，立即将插入到聊天后显示，按照demo里根据id插入或替换消息的方式来展示的话，会因发送成功回调时返回的实际messageId与之前不一致导致重复显示2条消息，

**Comment by CNHarrySun** [comment]
你好，这个在 4.0.1+2 版本中已修复。
