### ISSUE TITLE
pod install失败

### ISSUE THREAD

**Issue by insomniastay** [rongcloud/rongcloud-im-flutter-sdk#142]
[!] CocoaPods could not find compatible versions for pod "RongCloudIM/IMLib":
  In Podfile:
    rongcloud_im_plugin (from `.symlinks/plugins/rongcloud_im_plugin/ios`) was resolved to 0.0.1, which depends on
      RongCloudIM/IMLib (= 4.0.1)

None of your spec sources contain a spec satisfying the dependency: `RongCloudIM/IMLib (= 4.0.1)`.

**Comment by aliyoge** [comment]
`pod repo update`更新一下

**Comment by CNHarrySun** [comment]
现在 Flutter SDK 中都会指定最新的版本，需要更新下才可以。

**Comment by Sevencats** [comment]
RongCloudRTC (~> 4.0.3.3) was resolved to 4.0.3.3, which depends on
          RongCloudRTC/RongCallLib (= 4.0.3.3) was resolved to 4.0.3.3, which depends on
            RongCloudIM/IMLib (~> 4.0.3)

        rongcloud_im_plugin (from `.symlinks/plugins/rongcloud_im_plugin/ios`) was resolved to 0.0.1, which depends on
          RongCloudIM/IMLib (= 4.1.0)
 问题描述 ：不小心升级到了最新版本，导致出现了bug,现在需要回退到4.0.3.3去，所有配置文件更新正确，但pod install 总是报这个错。

**Comment by CNHarrySun** [comment]
pubspec.yaml 中指定版本：rongcloud_im_plugin: 4.0.3 然后再试下
