### ISSUE TITLE
ios报错

### ISSUE THREAD

**Issue by mengsiyitiaojie** [rongcloud/rongcloud-im-flutter-sdk#143]
4.0.1+1版本中 iOS发送消息后报错
![image](https://user-images.githubusercontent.com/55568326/88747708-e9b28a80-d181-11ea-885e-227efab5e69c.png)
请问是没有iOS哪里没有配置吗 导致没有注册该方法

**Comment by mengsiyitiaojie** [comment]
还有就是接受消息的方法是否重复了？
![image](https://user-images.githubusercontent.com/55568326/88747858-3ac27e80-d182-11ea-8ea1-4a9e14bc0f1f.png)
![image](https://user-images.githubusercontent.com/55568326/88747884-49a93100-d182-11ea-9196-46ea8d4e519f.png)
![image](https://user-images.githubusercontent.com/55568326/88747951-74938500-d182-11ea-98da-77e54e62d038.png)
发送消息后会出现两条一样的消息

**Comment by CNHarrySun** [comment]
1.请问你是接收什么消息会出现的 “该消息内容为空”，这个是 message 的 json 转 Message 时报的
2.  4.0.1+2 中修复了这个发送消息的 bug
