### ISSUE TITLE
嵌入原生iOS端时报错

### ISSUE THREAD

**Issue by yidahis** [rongcloud/rongcloud-im-flutter-sdk#144]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
 1.17.5
* 异常设备是 iOS 还是 Android，列出具体机型和系统
iOS
* 所调用的是什么 API 或者说是什么功能
RongIMClient.init()
* 完整的报错信息或者问题描述
我想在原生工程嵌入 flutter 版本的融云SDK， 但是启动程序后，进入嵌入的 flutter 页面时报错了。
`No implementation found for method init on channel rongcloud_im_plugin`

文档链接 https://github.com/rongcloud/rongcloud-im-flutter-sdk/tree/dev/doc
文档持续更新中……

**Comment by CNHarrySun** [comment]
你好，你看下是否导入了 rongcloud_im_plugin，是否导入成功
```
rongcloud_im_plugin: ^4.0.1+2
```
