### ISSUE TITLE
安卓系统中聊天出现的下载文件出现Bug

### ISSUE THREAD

**Issue by MaChengtianjiang** [rongcloud/rongcloud-im-flutter-sdk#145]
安卓系统下在FilePreviewPage页面中点击【开始下载】之后状态无法迁移至打开文件.
ios无此问题.

* 本地 Flutter 版本 1.17.3-stable 
* 融云flutter sdk 2.1.1, 4.0.x 版本皆有此问题 1.xx版本时期未曾出现过
* Android设备 华为TRT-AL00A,小米10
* 相关页面FilePreviewPage
* 相关接口RongIMClient.onDownloadMediaMessageResponse.
* 当使用安卓进入文件信息的下载完成的时候，通过isFileNeedDowload函数无法判断检查[fileMessage.localPath]路径文件是否存在时候,【return localFile.existsSync()】的返回总是为false.

可能是fileMessage.localPath的格式出了什么问题.

**Comment by CNHarrySun** [comment]
你好，4.0.1+3 版本中已经修复此问题。
