### ISSUE TITLE
如何自定义消息？？

### ISSUE THREAD

**Issue by lydat** [rongcloud/rongcloud-im-flutter-sdk#147]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
* 异常设备是 iOS 还是 Android，列出具体机型和系统
* 所调用的是什么 API 或者说是什么功能
* 完整的报错信息或者问题描述
* 提供问题发生时必要的日志，并以 txt 形式上传

文档链接 https://github.com/rongcloud/rongcloud-im-flutter-sdk/tree/dev/doc
文档持续更新中……

**Comment by CNHarrySun** [comment]
自定义消息参考：https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/doc/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B6%88%E6%81%AF.md
