### ISSUE TITLE
ImageMessage的sendUserInfo的extra发送以后，接收方收到的extra为null，只有ios有这个问题

### ISSUE THREAD

**Issue by zhangyc** [rongcloud/rongcloud-im-flutter-sdk#148]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
* 异常设备是 iOS 还是 Android，列出具体机型和系统
* 所调用的是什么 API 或者说是什么功能
* 完整的报错信息或者问题描述
* 提供问题发生时必要的日志，并以 txt 形式上传
 ImageMessage imgMsg = ImageMessage.obtain(imagePath);
    ///设置发送信息的额外的用户信息
    UserInfo userInfo=UserInfo();
    userInfo.name=Global.profile.user.nickname;
    userInfo.userId=Global.profile.user.appUserId.toString();
    userInfo.portraitUri=Global.profile.role.avatar;
    Map map=Map();
    map["roleId"]=Global.profile.role.roleId;
    userInfo.extra=jsonEncode(map);
    imgMsg.sendUserInfo=userInfo;
    Message msg = await RongIMClient.sendMessage(
        RCConversationType.Private, _targetId, imgMsg);
ImageMessage类型的消息加上userInfo.extra以后，在接收方extra为null。

 容云的版本号   rongcloud_im_plugin: ^4.0.1 

文档链接 https://github.com/rongcloud/rongcloud-im-flutter-sdk/tree/dev/doc
文档持续更新中……

**Comment by CNHarrySun** [comment]
你好，确实有这个问题，iOS 层发送消息时未解析 senderUserInfo 的 extra，已经修改，将会在下次更新时携带
