### ISSUE TITLE
[FR] beginDestructMessage 不要删除消息，而是更改消息状态

### ISSUE THREAD

**Issue by coodysk8er** [rongcloud/rongcloud-im-flutter-sdk#149]
beginDestructMessage计时结束时，消息被删除，这样阻碍了功能二次开发，例如：
需要让用户知道消息被阅读而不是不见了，请更新消息状态而不是删除。

为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.3)
[✓] Connected device (1 available)
```

* 异常设备是 iOS 还是 Android，列出具体机型和系统
通用

* 所调用的是什么 API 或者说是什么功能
rong_im_client.dart：

```
/// 开始焚烧消息
  static void messageBeginDestruct(Message message) async {
    Map messageMap = MessageFactory.instance.message2Map(message);
    Map map = {"message": messageMap};
    await _channel.invokeMethod(RCMethodKey.MessageBeginDestruct, map);
  }
```

* 完整的报错信息或者问题描述
没有错误

* 提供问题发生时必要的日志，并以 txt 形式上传
无

文档链接 https://github.com/rongcloud/rongcloud-im-flutter-sdk/tree/dev/doc
文档持续更新中……

**Comment by CNHarrySun** [comment]
你好，这个消息在 Native 底层就被删除了，所以 Flutter 层无法处理了。
消息查看后自动销毁，服务器不保留消息记录

**Comment by coodysk8er** [comment]
这个实现是不好的，因为没有办法支持需要用到的情况，例如：想展示一条信息这个消息被销毁了，而发送的人仍可查看发送了什么。

**Comment by CNHarrySun** [comment]
这个原先定的 IMLib 的逻辑，确实无法满足所有的场景。

**Comment by coodysk8er** [comment]
没有计划要更改或者满足fr？

**Comment by CNHarrySun** [comment]
这个暂时没有计划修改，因为市面上大部分这类功能都是这样处理的
