### ISSUE TITLE
是否需要单独实现onTokenIncorrect

### ISSUE THREAD

**Issue by yongzhengqi** [rongcloud/rongcloud-im-flutter-sdk#15]
在官方给的主意事项里，专门说了要实现onTokenIncorrect：https://support.rongcloud.cn/kb/MzMw

但在代码里只看到了android的example里有这个，请问需要单独实现吗？

**Comment by loginSin** [comment]
不需要单独实现该接口， connect 接口返回错误码 31004 即代表 onTokenIncorrect
下面是文档中对于该错误码的描述
 /*!
     Token无效

     @discussion Token无效一般有以下两种原因。
     一是token错误，请您检查客户端初始化使用的AppKey和您服务器获取token使用的AppKey是否一致；
     二是token过期，是因为您在开发者后台设置了token过期时间，您需要请求您的服务器重新获取token并再次用新的token建立连接。
     */
    RC_CONN_TOKEN_INCORRECT = 31004,

**Comment by yongzhengqi** [comment]
Roger that, thx!
