### ISSUE TITLE
SDK 4.0.1+5版本，每次hot reload后查询会话列表都返回空，重新run之后才返回数据

### ISSUE THREAD

**Issue by neusoftliang** [rongcloud/rongcloud-im-flutter-sdk#154]
SDK 4.0.1+5版本，每次hot reload后查询会话列表都返回空，重新run之后才返回数据,当前SDK连接状态是34001，是这个原因造成的吗

**Comment by freew01f** [comment]
因为你获取列表时候 Client还没链接成功吧

**Comment by CNHarrySun** [comment]
34001 是连接已存在，可以调用 disconnect 之后再登录试下。
