### ISSUE TITLE
支持发送本地或远程视频吗？时长是多少？

### ISSUE THREAD

**Issue by lydat** [rongcloud/rongcloud-im-flutter-sdk#157]

**Comment by CNHarrySun** [comment]
你好，参考下 https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/doc/%E5%B0%8F%E8%A7%86%E9%A2%91.md

发送的是本地视频，时长在 iOS 和 Android 的 wrapper 层限制了 10s

**Comment by lydat** [comment]
> 你好，参考下 https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/doc/%E5%B0%8F%E8%A7%86%E9%A2%91.md
> 
> 发送的是本地视频，时长在 iOS 和 Android 的 wrapper 层限制了 10s
