### ISSUE TITLE
无论下载整个包还是example ，Android studio打开不完整

### ISSUE THREAD

**Issue by dukezhao** [rongcloud/rongcloud-im-flutter-sdk#16]
无论下载整个包还是example ，Android studio打开不完整?还没写完吗？

**Comment by loginSin** [comment]
这个工程本质上是 Flutter 项目
1.项目路径执行 flutter packages get 来下载 Flutter Plugin
2.Android studio 打开 _example/android_ 目录，不是根目录也不是 example 目录

**Comment by dukezhao** [comment]
flutter的话跑起来闪退了

**Comment by loginSin** [comment]
**flutter的话跑起来闪退了**  仅通过这样的描述没办法定位问题啊，是否可以提供必要的 log？

**Comment by ysyniko** [comment]
> flutter的话跑起来闪退了

我也是，跑起来后直接闪退，
