### ISSUE TITLE
如何清空某一用户的聊天记录

### ISSUE THREAD

**Issue by lydat** [rongcloud/rongcloud-im-flutter-sdk#160]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
* 异常设备是 iOS 还是 Android，列出具体机型和系统
* 所调用的是什么 API 或者说是什么功能
* 完整的报错信息或者问题描述
* 提供问题发生时必要的日志，并以 txt 形式上传

文档链接 https://github.com/rongcloud/rongcloud-im-flutter-sdk/tree/dev/doc
文档持续更新中……

**Comment by CNHarrySun** [comment]
需要删除会话以及会话中的消息，如果下拉是会拉取远端历史消息，还需要将远端历史消息删除（clearHistoryMessages）

**Comment by lydat** [comment]
> 需要删除会话以及会话中的消息，如果下拉是会拉取远端历史消息，还需要将远端历史消息删除（clearHistoryMessages）

recordTime 你知道这个参数是干嘛的吗？

**Comment by CNHarrySun** [comment]
消息的时间戳。

///清除历史消息
  ///
  ///[conversationType] 会话类型，参见枚举 [RCConversationType]
  ///
  ///[targetId] 会话 id
  ///
  ///[recordTime] 清除消息时间戳，【0 <= recordTime <= 当前会话最后一条消息的 sentTime,0 清除所有消息，其他值清除小于等于 recordTime 的消息】
  ///
  ///[clearRemote] 是否同时删除服务端消息
  ///
  ///[finished] 回调结果
  ///
  /// 此方法可以清除服务器端历史消息和本地消息，如果清除服务器端消息必须先开通历史消息云存储功能。例如，您不想从服务器上获取更多的历史消息，通过指定 recordTime 并设置 clearRemote 为 YES 清除消息，成功后只能获取该时间戳之后的历史消息。如果 clearRemote 传 NO，只会清除本地消息。
  static clearHistoryMessages(int conversationType, String targetId,
      int recordTime, bool clearRemote, Function(int code) finished) async {

**Comment by lydat** [comment]
> 消息的时间戳。
> 
> ///清除历史消息
> ///
> ///[conversationType] 会话类型，参见枚举 [RCConversationType]
> ///
> ///[targetId] 会话 id
> ///
> ///[recordTime] 清除消息时间戳，【0 <= recordTime <= 当前会话最后一条消息的 sentTime,0 清除所有消息，其他值清除小于等于 recordTime 的消息】
> ///
> ///[clearRemote] 是否同时删除服务端消息
> ///
> ///[finished] 回调结果
> ///
> /// 此方法可以清除服务器端历史消息和本地消息，如果清除服务器端消息必须先开通历史消息云存储功能。例如，您不想从服务器上获取更多的历史消息，通过指定 recordTime 并设置 clearRemote 为 YES 清除消息，成功后只能获取该时间戳之后的历史消息。如果 clearRemote 传 NO，只会清除本地消息。
> static clearHistoryMessages(int conversationType, String targetId,
> int recordTime, bool clearRemote, Function(int code) finished) async {

好像没效果，一直报33077，不过清除会话到是生效了
![image](https://user-images.githubusercontent.com/36094163/92461471-e89e5f80-f1fb-11ea-8fb4-476c5bf6ea08.png)

**Comment by CNHarrySun** [comment]
clearRemote 传 false 吧，这个需要开通历史消息云存储功能
