### ISSUE TITLE
getConversationList消息列表的用户头像和昵称

### ISSUE THREAD

**Issue by zhuzhev** [rongcloud/rongcloud-im-flutter-sdk#163]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
* 异常设备是 iOS 还是 Android，列出具体机型和系统
* 所调用的是什么 API 或者说是什么功能
* 完整的报错信息或者问题描述
* 提供问题发生时必要的日志，并以 txt 形式上传

文档链接 https://github.com/rongcloud/rongcloud-im-flutter-sdk/tree/dev/doc
文档持续更新中……

通过getConversationList获取到的消息列表中Conversation.latestMessageContent.sendUserInfo只能获取最后发送消息的用户信息，怎么固定获取消息列表中聊天对象的头像和昵称

**Comment by CNHarrySun** [comment]
您需要通过 Conversation 的 targetId 和 conversationType 来获取聊天对象的头像和昵称，头像和昵称需要保存在您的 App 本地或者服务端。
