### ISSUE TITLE
有时候发送消息 对方接收不到  是什么原因啊

### ISSUE THREAD

**Issue by mengsiyitiaojie** [rongcloud/rongcloud-im-flutter-sdk#165]
![image](https://user-images.githubusercontent.com/55568326/93450472-98fd1980-f908-11ea-8b7e-60f0954062bb.png)

**Comment by CNHarrySun** [comment]
用户 ID 为 18 的用户没有上传 DeviceId，需要参考下面的连接设置
远程推送的实现：https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/doc/%E6%9C%AC%E5%9C%B0%E9%80%9A%E7%9F%A5%E4%B8%8E%E8%BF%9C%E7%A8%8B%E6%8E%A8%E9%80%81%E7%9A%84%E5%AE%9E%E7%8E%B0.md
