### ISSUE TITLE
有聊天界面吗？还是需要自己实现聊天界面？

### ISSUE THREAD

**Issue by mushanlianshi** [rongcloud/rongcloud-im-flutter-sdk#167]
有聊天界面吗？还是需要自己实现聊天界面？

**Comment by CNHarrySun** [comment]
Flutter SDK 是即时通讯的接口，不带 UI 的，[imkit-flutter-quickstart](https://github.com/rongcloud/imkit-flutter-quickstart) 这是一个集成 Flutter SDK 的简易的 demo
