### ISSUE TITLE
如何让android绕过file://的判断，因为我现在的实现方式是，图片存阿里云，然后返回的图片地址存放在imageuri上面提交，苹果手机可以提交,android报如下错误

### ISSUE THREAD

**Issue by lydat** [rongcloud/rongcloud-im-flutter-sdk#169]
![image](https://user-images.githubusercontent.com/36094163/95729150-09504e00-0caf-11eb-8052-e34466a7791d.png)

**Comment by zoulu123** [comment]
这个你的判断 ios 和 Android 区分处理，Android 本地地址是必须带 file:// 的，example 里面有相关处理的，你可以参考一下
