### ISSUE TITLE
一发消息报错

### ISSUE THREAD

**Issue by dukezhao** [rongcloud/rongcloud-im-flutter-sdk#17]
E/MethodChannel#rongcloud_im_plugin( 8918): Failed to handle method call
E/MethodChannel#rongcloud_im_plugin( 8918): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null
 object reference
E/MethodChannel#rongcl

**Comment by loginSin** [comment]
发送了什么消息？根据描述只能看出来是 java 层的空指针问题，但是需要更详细的数据定位具体的代码
