### ISSUE TITLE
消息发不出去MissingLibraryException: libsqlite.so

### ISSUE THREAD

**Issue by zhangyc** [rongcloud/rongcloud-im-flutter-sdk#175]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
* 异常设备是 iOS 还是 Android，列出具体机型和系统
* 所调用的是什么 API 或者说是什么功能
* 完整的报错信息或者问题描述
* 提供问题发生时必要的日志，并以 txt 形式上传

文档链接 https://github.com/rongcloud/rongcloud-im-flutter-sdk/tree/dev/doc
文档持续更新中……
ava.lang.RuntimeException: Unable to bind to service io.rong.imlib.ipc.RongService@325af75 with Intent { cmp=com.planet.pinponapp/io.rong.imlib.ipc.RongService (has extras) }: io.rong.imlib.relinker.MissingLibraryException: libsqlite.so

完整log
 java.lang.RuntimeException: Unable to bind to service io.rong.imlib.ipc.RongService@325af75 with Intent { cmp=com.planet.pinponapp/io.rong.imlib.ipc.RongService (has extras) }: io.rong.imlib.relinker.MissingLibraryException: libsqlite.so
E/AndroidRuntime(14693): 	at android.app.ActivityThread.handleBindService(ActivityThread.java:4266)
E/AndroidRuntime(14693): 	at android.app.ActivityThread.access$1700(ActivityThread.java:255)
E/AndroidRuntime(14693): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
E/AndroidRuntime(14693): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(14693): 	at android.os.Looper.loop(Looper.java:230)
E/AndroidRuntime(14693): 	at android.app.ActivityThread.main(ActivityThread.java:7768)
E/AndroidRuntime(14693): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14693): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:508)
E/AndroidRuntime(14693): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
E/AndroidRuntime(14693): Caused by: io.rong.imlib.relinker.MissingLibraryException: libsqlite.so
E/AndroidRuntime(14693): 	at io.rong.imlib.relinker.ApkLibraryInstaller.installLibrary(ApkLibraryInstaller.java:128)
E/AndroidRuntime(14693): 	at io.rong.imlib.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:180)
E/AndroidRuntime(14693): 	at io.rong.imlib.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
E/AndroidRuntime(14693): 	at io.rong.imlib.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:92)
E/AndroidRuntime(14693): 	at io.rong.imlib.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:197)
E/AndroidRuntime(14693): 	at io.rong.imlib.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
E/AndroidRuntime(14693): 	at io.rong.imlib.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:92)
E/AndroidRuntime(14693): 	at io.rong.imlib.NativeObject.<init>(NativeObject.java:28)
E/AndroidRuntime(14693): 	at io.rong.imlib.NativeClient.init(NativeClient.java:181)
E/AndroidRuntime(14693): 	at io.rong.imlib.LibHandlerStub.<init>(LibHandlerStub.java:58)
E/AndroidRuntime(14693): 	at io.rong.imlib.ipc.RongService.onBind(RongService.java:37)
E/AndroidRuntime(14693): 	at android.app.ActivityThread.handleBindService(ActivityThread.java:4251)
E/AndroidRuntime(14693): 	... 8 more

**Comment by supermebing** [comment]
请问解决了么？

**Comment by zhangyc** [comment]
解决了


在2020年11月30日 14:40，supermebing 写道：

请问解决了么？

**Comment by zhangyc** [comment]
> 请问解决了么？
清一下as的缓存
