### ISSUE TITLE
android启动时闪退

### ISSUE THREAD

**Issue by zhangyc** [rongcloud/rongcloud-im-flutter-sdk#179]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
 1.2
* 异常设备是 iOS 还是 Android，列出具体机型和系统
android
* 所调用的是什么 API 或者说是什么功能

* 完整的报错信息或者问题描述
 [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, null, null, java.util.ConcurrentModificationException
E/flutter (18081): 	at java.util.ArrayList$Itr.next(ArrayList.java:860)
E/flutter (18081): 	at io.rong.flutter.imlib.RCIMFlutterWrapper.fetchAllMessageMapper(RCIMFlutterWrapper.java:1949)
E/flutter (18081): 	at io.rong.flutter.imlib.RCIMFlutterWrapper.connect(RCIMFlutterWrapper.java:531)
E/flutter (18081): 	at io.rong.flutter.imlib.RCIMFlutterWrapper.onFlutterMethodCall(RCIMFlutterWrapper.java:151)
E/flutter (18081): 	at io.rong.flutter.imlib.RongcloudImPlugin.onMethodCall(RongcloudImPlugin.java:21)
E/flutter (18081): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (18081): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (18081): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (18081): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (18081): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (18081): 	at android.os.Looper.loop(Looper.java:181)
E/flutter (18081): 	at android.app.ActivityThread.main(ActivityThread.java:7592)
E/flutter (18081): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (18081): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/flutter (18081): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/flutter (18081): )
E/flutter (18081): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter (18081): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter (18081): <asynchronous suspension>
E/flutter (18081): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (18081): #3      RongIMClient.connect (package:rongcloud_im_plugin/src/rong_im_client.dart:38:36)
E/flutter (18081): #4      PinponIM.connect (package:pinponapp/common/pinpon_util/pinpon_im.dart:38:18)
E/flutter (18081): #5      PinponIM.init (package:pinponapp/common/pinpon_util/pinpon_im.dart:32:26)
E/flutter (18081): #6      main (package:pinponapp/main.dart:26:18)
E/flutter (18081): #7      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (18081): #8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (18081): #9      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (18081): #10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (18081): #11     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (18081): #12     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (18081): #13     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (18081): #14     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (18081): #15     Global.init (package:pinponapp/common/global.dart)
E/flutter (18081): #16     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (18081): #17     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (18081): #18     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (18081): #19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (18081): #20     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (18081): #21     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (18081): #22     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (18081): #23     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (18081): #24     SpUtil.getInstance (package:sp_util/sp_util.dart)
E/flutter (18081): #25     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (18081): #26     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (18081): #27     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (18081): #28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (18081): #29     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (18081): #30     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (18081): #31     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (18081): #32     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (18081): #33     BasicLock.synchronized (package:synchronized/src/basic_lock.dart)
E/flutter (18081): #34     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (18081): #35     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (18081): #36     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (18081): #37     Future._propagateToListeners.handleValueCallback (dar
I/Statistics(18081): start
* 提供问题发生时必要的日志，并以 txt 形式上传

文档链接 https://github.com/rongcloud/rongcloud-im-flutter-sdk/tree/dev/doc
文档持续更新中……

**Comment by zoulu123** [comment]
你的 sdk 版本是多少？尝试下升级到最新的会有问题吗？
