### ISSUE TITLE
Flutter IOS推送,swift版本能否更新一下

### ISSUE THREAD

**Issue by AcmeField** [rongcloud/rongcloud-im-flutter-sdk#180]
感谢

**Comment by supermebing** [comment]
我也遇到这个问题  是因为swift版本的问题么 ？  AppDelegate.swift  代码拿过来报错

**Comment by AcmeField** [comment]
希望融云官方能够补充一些flutter ios下除了证书,跟swift相关的具体配置和demo。 感谢各位开发同学。 应该也有不少后端直接转flutter的同学 ios和安卓基础比较薄弱

**Comment by AcmeField** [comment]
> 我也遇到这个问题 是因为swift版本的问题么 ？ AppDelegate.swift 代码拿过来报错

搞定了 兄弟

`
import UIKit
import Flutter
import RongIMLib
import rongcloud_im_plugin

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate{


    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
        ) -> Bool {
        GeneratedPluginRegistrant.register(with: self)
        
        // 推送处理 1 (申请推送权限)
        registerUserNotification()
        
       // 获取推送数据
       let remoteNotificationUserInfo = launchOptions?[UIApplication.LaunchOptionsKey.remoteNotification]

       // 向 Flutter 层传递推送数据
       if let userInfo = remoteNotificationUserInfo {
           DispatchQueue.main.asyncAfter(deadline: .now()+0.5) {
               RCIMFlutterWrapper.shared().sendData(toFlutter:userInfo as! [AnyHashable : Any])
           };
       }
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }
    
    func registerUserNotification(){
        if #available(iOS 10.0, *) {
            let center = UNUserNotificationCenter.current()
            center.requestAuthorization(options: [.alert, .sound, .badge], completionHandler: { (_, _) in })
            center.delegate = self
        } else {
            let settings = UIUserNotificationSettings(types: [.alert, .sound, .badge], categories: nil)
            UIApplication.shared.registerUserNotificationSettings(settings)
        }
        UIApplication.shared.registerForRemoteNotifications()
    }
    
    
    // 推送处理 2 (注册用户通知设置)
    override func application(_ application: UIApplication, didRegister notificationSettings: UIUserNotificationSettings) {
        application.registerForRemoteNotifications()
    }
    
    

    // 推送处理 3 (上传DeviceToken)
     override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        RCIMClient.shared()?.setDeviceTokenData(deviceToken)
        
     }
    
    override func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any]) {
       RCIMFlutterWrapper.shared().sendData(toFlutter:userInfo)
    }
}
`

害我白白耽误人家人工客服2天

**Comment by AcmeField** [comment]
> 我也遇到这个问题 是因为swift版本的问题么 ？ AppDelegate.swift 代码拿过来报错

你还有什么错误  提出来 我看看我有没有遇到

**Comment by supermebing** [comment]
我这边没报错  但是还是收不到apns的通知    现在再调系统消息的已读状态

**Comment by supermebing** [comment]
> > 我也遇到这个问题 是因为swift版本的问题么 ？ AppDelegate.swift 代码拿过来报错
> 
> 你还有什么错误 提出来 我看看我有没有遇到

我按照你这个重新改了   安装后 退出后台还是无法收到推送 不知道怎么回事  可否加个微信或者qq

**Comment by AcmeField** [comment]
检查融云配置的证书配置个测试环境,xcode 那边启动时要开起background modes -> remote notification + notification 2个xcode启动配置，profile 要测试环境。

**Comment by 1xiaocainiao** [comment]
我也出现这种情况了，但是用pusher这个工具又是能够收到推送的，就是收不到融云的推送,有谁知道怎么回事吗,融云后台证书都换了好几次了

**Comment by supermebing** [comment]
> 我也出现这种情况了，但是用pusher这个工具又是能够收到推送的，就是收不到融云的推送,有谁知道怎么回事吗,融云后台证书都换了好几次了

需要修改AppDelegate.m文件

**Comment by CNHarrySun** [comment]
远程推送收不到，需要参考 [官方文档](https://docs.rongcloud.cn/v4/views/im/noui/guide/private/notify/push/ios.html) 上传证书和添加必要的代码，上传证书后 30 分钟才会生效，生效后可以使用开发者后台“应用标识 -> 设置推送 -> push 测试”来进行测试
