### ISSUE TITLE
音频无法播放

### ISSUE THREAD

**Issue by Jiang-bikuan** [rongcloud/rongcloud-im-flutter-sdk#183]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* flutter 1.22.4
* android 小米MIX3 android 10.0
* 播放音频功能
* 聊天页面点击音频条目报错，无法播放

didTapMessageItem RC:HQVCMsg

* V/MediaHTTPService( 1307): MediaHTTPService(android.media.MediaHTTPService@e2cc6df): Cookies: null
V/MediaHTTPService( 1307): makeHTTPConnection: CookieManager created: java.net.CookieManager@d22cf2c
V/MediaHTTPService( 1307): makeHTTPConnection(android.media.MediaHTTPService@e2cc6df): cookieHandler: java.net.CookieManager@d22cf2c Cookies: null
E/MediaPlayerNative( 1307): error (1, -2147483648)
E/FlutterSoundPlugin( 1307): startPlayer() exception
E/flutter ( 1307): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Exception: PlatformException(ERR_UNKNOWN, ERR_UNKNOWN, Prepare failed.: status=0x1, null)
E/flutter ( 1307): #0      FlutterSound._startPlayer (package:flutter_sound/flutter_sound.dart:378:7)
E/flutter ( 1307): <asynchronous suspension>
E/flutter ( 1307): #1      FlutterSound.startPlayer (package:flutter_sound/flutter_sound.dart:383:51)
E/flutter ( 1307): #2      MediaUtil.startPlayAudio (package:shopping_flutter/utils/media_util.dart:150:18)
E/flutter ( 1307): #3      _ConversationState.didTapMessageItem (package:shopping_flutter/pages/rongyun/Conversation.dart:339:28)
E/flutter ( 1307): #4      _MessageContentListState.didTapMessageItem (package:shopping_flutter/pages/rongyun/message_content_list.dart:214:14)
E/flutter ( 1307): #5      _ConversationItemState.__onTapedMesssage (package:shopping_flutter/pages/rongyun/conversation_item.dart:261:18)
E/flutter ( 1307): #6      _ConversationItemState.buildMessageWidget.<anonymous closure> (package:shopping_flutter/pages/rongyun/conversation_item.dart:344:25)
E/flutter ( 1307): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter ( 1307): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter ( 1307): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter ( 1307): #10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
E/flutter ( 1307): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter ( 1307): #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
E/flutter ( 1307): #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter ( 1307): #14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter ( 1307): #15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter ( 1307): #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter ( 1307): #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter ( 1307): #18     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 1307): #19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 1307): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 1307): #21     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter ( 1307): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)

文档链接 https://github.com/rongcloud/rongcloud-im-flutter-sdk/tree/dev/doc
文档持续更新中……

**Comment by Leon-ele** [comment]
audioPlayer 插件不能播放 AAC格式，换个插件flutterSound 可以播放，
一起爬坑 QQ群：797217852

**Comment by Sevencats** [comment]
问题描述:不小心更新到最新版本，发现出现了bug,回退到稳定版本，但发现无论如何修改配置文件，始终无法拿到4.0.4版本。。
In snapshot (Podfile.lock):
    RongCloudIM/IMLib (= 4.0.4, ~> 4.0.3)

  In Podfile:
    rongcloud_im_plugin (from `.symlinks/plugins/rongcloud_im_plugin/ios`) was resolved to 0.0.1, which depends on
      RongCloudIM/IMLib (= 4.1.0)

**Comment by Sevencats** [comment]
![截屏2020-12-31 下午5 49 05](https://user-images.githubusercontent.com/56510404/103404989-7aa5eb80-4b90-11eb-9227-e362fa5ef78e.png)

**Comment by CNHarrySun** [comment]
pubspec.yaml 中指定版本：rongcloud_im_plugin: 4.0.3 然后再试下

**Comment by Sevencats** [comment]
依旧不起作用
![截屏2021-01-05 下午4 23 49](https://user-images.githubusercontent.com/56510404/103622970-6720c900-4f72-11eb-9597-c58e7d6d090c.png)

**Comment by Sevencats** [comment]
> pubspec.yaml 中指定版本：rongcloud_im_plugin: 4.0.3 然后再试下

指定了，删除缓存文件，重新pub get pub upgrade pod install ,还是报如之前的错误。。更新4.1.0没有问题，回退回去就始终报一样的错误。
![截屏2021-01-05 下午4 27 02](https://user-images.githubusercontent.com/56510404/103623271-da2a3f80-4f72-11eb-9d96-95761d9e87e3.png)
