### ISSUE TITLE
聊天界面：下拉加载历史消息，将消息数组拼接并且保证界面还是定位在上拉加载前的会话位置呢？

### ISSUE THREAD

**Issue by lionnner** [rongcloud/rongcloud-im-flutter-sdk#184]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
* 异常设备是 iOS 还是 Android，列出具体机型和系统
* 所调用的是什么 API 或者说是什么功能
* 完整的报错信息或者问题描述
* 提供问题发生时必要的日志，并以 txt 形式上传

文档链接 https://github.com/rongcloud/rongcloud-im-flutter-sdk/tree/dev/doc
文档持续更新中……

**Comment by Leon-ele** [comment]
listView 每次刷新消息都会重新初始化监听，修改controller 的初始化滚动位置为 上次保留的位置即可

**Comment by lionnner** [comment]
如果没有使用 reserve，下拉加载的时候， scrollcontroller的偏移量为 0啊，数组拼接了数据，不好计算偏移量啊。

**Comment by Leon-ele** [comment]
> 如果没有使用 reserve，下拉加载的时候， scrollcontroller的偏移量为 0啊，数组拼接了数据，不好计算偏移量啊。

不是0 ，state没变会保存 偏移量，重新赋值即可

**Comment by Leon-ele** [comment]
兄弟们 QQ群一起爬坑吧：797217852

**Comment by CNHarrySun** [comment]
可以这样试下：
记录下 mPosition = _scrollController.position.pixels;
然后更新时 this._scrollController = ScrollController(initialScrollOffset: mPosition);

**Comment by lionnner** [comment]
> 可以这样试下：
> 记录下 mPosition = _scrollController.position.pixels;
> 然后更新时 this._scrollController = ScrollController(initialScrollOffset: mPosition);

下拉的时候 scrollcontroller的偏移量为0，数组为[a1,a2,a3....],下拉加载了更多后 数组为[c1,c2,...a1,a2,a3]
如何保证偏移量到a1呢？

**Comment by zoulu123** [comment]
你能记录到 a1 的位置 position 吗？然后用 api 滚动到对应的位置

**Comment by lionnner** [comment]
> 你能记录到 a1 的位置 position 吗？然后用 api 滚动到对应的位置

a1 此时的position就是 0 啊！
