### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by lizaihao** [rongcloud/rongcloud-im-flutter-sdk#185]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  E:\study\rongcloud-im-flutter-sdk\example\build\app\intermediates\merged_manifests\debug\AndroidManifest.xml:31: AAPT: error: attribute android:requestLegacyExternalStorage not found.

  error: failed processing manifest.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin camera...
Running Gradle task 'assembleAarRelease'...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'camera'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 611ms

Exception: The plugin camera could not be built due to the issue above.

**Comment by jhfkf** [comment]
你的解决了吗？更新 camera ？

**Comment by ios-yifan** [comment]
您好，请问现在是否可以正常运行demo？

**Comment by ios-yifan** [comment]
您好，当前问题即将关闭，后续使用遇到任何问题可以在融云开发者后台提交工单，会有我们的技术人员进行及时处理。
