### ISSUE TITLE
当content为null时 Message的toString()方法报错

### ISSUE THREAD

**Issue by neusoftliang** [rongcloud/rongcloud-im-flutter-sdk#189]
sdk版本4.1.0  当content为null时 Message的toString()方法报错 
提示encode()解析错误

**Comment by zoulu123** [comment]
你是在 flutter 层 toString 还是 Android 层，具体错误的代码发出来看下

**Comment by ios-yifan** [comment]
您好，最新版本已适配空安全，你可以升级到最新版本测试一下。

**Comment by ios-yifan** [comment]
您好，当前问题即将关闭，后续使用遇到任何问题可以在融云开发者后台提交工单，会有我们的技术人员进行及时处理。
