### ISSUE TITLE
自定义消息问题

### ISSUE THREAD

**Issue by shingohu** [rongcloud/rongcloud-im-flutter-sdk#190]
目前自定义消息采用注册反射方式进行解析极其不方便,不灵活,建议升级一个新的自定义方法,具体解析交由应用层自己处理,api只需携带自定义消息的类型和数据给到应用层

**Comment by zoulu123** [comment]
非常感谢您的意见，我们已经在最新版本加入了此处理方式，您切换到 release 分支即可看到具体代码在，rong_im_client.dart 文件中的 messageDecoders ，您可以查看下
