### ISSUE TITLE
Can  you migrate example to flutter2.0 ？示例可以升级到flutter2.0吗

### ISSUE THREAD

**Issue by suyie001** [rongcloud/rongcloud-im-flutter-sdk#191]
Can  you migrate example to flutter2.0 ？示例可以升级到flutter2.0吗

**Comment by zzg19901210** [comment]
同样的问题

**Comment by zoulu123** [comment]
示例只是作为参考使用，你们可以用 flutter2.0 作为你们应用的开发环境版本，然后可适度参考我们 example 的代码，或者尝试完全迁移，后续我们会考虑升级的

**Comment by sherwin** [comment]
example  还没2.0 太难受了 打开全红, 快点出2.0吧

**Comment by ios-yifan** [comment]
您好，现有版本已经升级
