### ISSUE TITLE
连接融云服务器时，回调没有发生

### ISSUE THREAD

**Issue by QuintazZ** [rongcloud/rongcloud-im-flutter-sdk#192]
我在调用connect时，偶尔会有callback无法回调的情况，导致我无法进入下一步，无法进行通信相关任何操作，

**Comment by ios-yifan** [comment]
您好，请问当前还有遇到此问题吗？
可以参考下面内容导出一份日志我们查看一下。
iOS：

导出日志请参考:http://support.rongcloud.cn/kb/NDI0

Android

您按以下步骤抓取一份完整 log

log 抓取步骤

卸载并重新安装应用
在命令窗口输入 adb logcat -v time > xxxx.log (在启动应用之前运行, 否则可能 log 不全)
启动应用并进行相关操作, 直到出现您所遇到的问题
ctrl + c 结束log 抓取

**Comment by ios-yifan** [comment]
您好，当前问题即将关闭，后续使用遇到任何问题可以在融云开发者后台提交工单，会有我们的技术人员进行及时处理。
