### ISSUE TITLE
无法下载aar文件

### ISSUE THREAD

**Issue by misskter** [rongcloud/rongcloud-im-flutter-sdk#194]
我的错误是这样的下载地址访问是403
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not download im_lib.aar (cn.rongcloud.sdk:im_lib:4.1.1)
      > Could not get resource 'https://dl.bintray.com/rongcloud/maven/cn/rongcloud/sdk/im_lib/4.1.1/im_lib-4.1.1.aar'.
         > Could not GET 'https://dl.bintray.com/rongcloud/maven/cn/rongcloud/sdk/im_lib/4.1.1/im_lib-4.1.1.aar'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Exception: Gradle task assembleDebug failed with exit code 1

我的开发环境是这样的：
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.19042.928], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Android Studio (version 3.5)
[√] Connected device (2 available)

• No issues found!

**Comment by haoXu1990** [comment]
请问你解决了吗，我也遇到了这个问题，跑安卓的时候才会出现

**Comment by ios-yifan** [comment]
您好，请问当前问题是否解决？

**Comment by haoXu1990** [comment]
> 您好，请问当前问题是否解决？

已经解决了。
问题出在当前 maven 中心仓库已经不维护了
融云官网有新的 maven 仓库地址里面

**Comment by ios-yifan** [comment]
好的。
