### ISSUE TITLE
kotlin怎么注册自定义消息

### ISSUE THREAD

**Issue by suyie001** [rongcloud/rongcloud-im-flutter-sdk#195]
flutter2.0.6版本，默认创建的项目的android 为kotlin主activity，请问怎么注册自定义消息？还有自定义消息定义在kotlin项目目录里吗？我目前自己摸索了两天得到错误代码33003。

**Comment by Stuazt** [comment]
同学，你这个不是issue啊，去看文档或者问客服啊。。。issue是这么用的吗？
