### ISSUE TITLE
接收web携带的用户时无法解析

### ISSUE THREAD

**Issue by keacefull** [rongcloud/rongcloud-im-flutter-sdk#197]
当web端携带用户信息时，user下的id为int类型时，fultter无法获取到用户信息。

**Comment by ios-yifan** [comment]
SDK 中 userinfo 中的 id 是以字符串的形式存在的。

**Comment by ios-yifan** [comment]
您好，当前问题即将关闭，后续使用遇到任何问题可以在融云开发者后台提交工单，会有我们的技术人员进行及时处理。
