### ISSUE TITLE
安卓的https://dl.bintray.com/rongcloud/maven服务停了,有替代方案吗？

### ISSUE THREAD

**Issue by MaChengtianjiang** [rongcloud/rongcloud-im-flutter-sdk#198]
老项目还使用你们5.1.0的版本，但是安卓这个依赖无法下下来。
项目flutter sdk 1.22.6。
看了一下bintray官网应该是服务停止了。
但是在这个下面的依赖现在应该怎么获取。
maven {url  "https://dl.bintray.com/rongcloud/maven"}

**Comment by loginSin** [comment]
请参考该文档 https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/doc/Android%20Maven%20%E4%BB%93%E5%BA%93%E5%8F%98%E6%9B%B4%E8%AF%B4%E6%98%8E.md

**Comment by loginSin** [comment]
请参考该文档 https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/doc/Android%20Maven%20%E4%BB%93%E5%BA%93%E5%8F%98%E6%9B%B4%E8%AF%B4%E6%98%8E.md
