### ISSUE TITLE
Failure when query

### ISSUE THREAD

**Issue by learyR** [rongcloud/rongcloud-im-flutter-sdk#2]
老哥加油，好像还有很多问题

**Comment by loginSin** [comment]
你好，如果遇到了问题，请贴一下问题的具体信息

**Comment by learyR** [comment]
---
    10:43:15.461 1484 info flutter.tools [  +41 ms] I/RongLog (25084): [ RongIMClient ] RongIMClient
    10:43:15.487 1485 info flutter.tools [  +25 ms] I/RongLog (25084): [ RongIM ] init : 
    com.leary.flutter_wan
    10:43:15.677 1493 info flutter.tools [        ] D/RongLog (25084): [ RongIMClient ] isPushEnabled:true
    10:43:15.677 1494 info flutter.tools [        ] D/RongLog (25084): [ RongIMClient ] init : 
    com.leary.flutter_wan, com.leary.flutter_wan, io.flutter.app.FlutterApplication@ef72517
    10:43:15.751 1500 info flutter.tools [  +72 ms] D/RongLog-Push[RongPushClient](25084): 
    isSelfCertificate:false
    10:43:15.751 1501 info flutter.tools [        ] E/RongLog-Push[PushConfig](25084): appid or appkey can't 
    be empty when enable MI push !
    10:43:15.751 1502 info flutter.tools [        ] E/RongLog-Push[PushConfig](25084): appid or appkey can't 
    be empty when enable MEIZU push !
    10:43:15.795 1503 info flutter.tools [  +43 ms] D/RongLog-Push[PushManager](25084): 
    preferPushType:RONG; cachedPushType:RONG
    10:43:15.795 1504 info flutter.tools [        ] D/RongLog-Push[PushConfig](25084): enabledPushTypes:
    10:43:15.795 1505 info flutter.tools [        ] D/RongLog-Push[PushManager](25084): 
     isConfigChanged:false; cachedTypes:
    10:43:15.795 1506 info flutter.tools [        ] D/RongLog-Push[PushManager](25084): register. 
    type:RONG
    10:43:15.795 1507 info flutter.tools [        ] D/RongLog-Push[PushConfig](25084): enabledPushTypes:
    10:43:15.795 1508 info flutter.tools [        ] I/RongLog (25084): [ RongIMClient ] mReconnectInterval 10
    10:43:15.996 1511 info flutter.tools [        ] D/RongLog (25084): [ RongExtensionManager ] init
    10:43:15.996 1512 info flutter.tools [        ] I/RongLog (25084): [ RongExtensionManager ] Can't find 
    com.melink.bqmmplugin.rc.BQMMExtensionModule
    10:43:15.996 1513 info flutter.tools [        ] I/RongLog (25084): [ RongExtensionManager ] Can't find 
    io.rong.sticker.StickerExtensionModule
    10:43:15.996 1515 info flutter.tools [        ] I/RongLog (25084): [ DefaultExtensionModule ] not config 
    rc_realtime_support_conversation_types in rc_config.xml
    10:43:15.996 1516 info flutter.tools [        ] I/RongLog (25084): [ RongExtensionManager ] 
    registerExtensionModule DefaultExtensionModule
    10:43:15.996 1517 info flutter.tools [        ] I/RongLog (25084): [ InternalModuleManager ] init
    10:43:15.996 1518 info flutter.tools [        ] I/RongLog (25084): [ InternalModuleManager ] Can not find 
    RongCallModule.
    10:43:15.996 1519 info flutter.tools [        ] I/RongLog (25084): [ InternalModuleManager ] onInitialized
    10:43:15.996 1520 info flutter.tools [        ] D/RongLog (25084): [ AlbumBitmapCacheHelper ] init
    10:43:15.996 1521 info flutter.tools [        ] D/RongLog (25084): [ ConnectChangeReceiver ] intent : 
    Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) }
    10:43:15.996 1522 info flutter.tools [        ] D/RongLog (25084): [ ConnectChangeReceiver ] network : 
    true true
     10:43:15.996 1525 info flutter.tools [        ] E/RongLog (25084): [ RongIMClient ] token is empty!
     10:43:17.095 1529 info flutter.tools [        ] D/RongLog (25084): [ RongIMClient ] set token
    10:43:17.109 1531 info flutter.tools [   +3 ms] D/RongLog (25084): [ RongIMClient ] [connect] 
    ConnectRunnable for connect
    10:43:17.255 1532 info flutter.tools [ +143 ms] I/RongLog (25084): [ RongIM ] RongIM 
    setOnReceiveMessageListener
    10:43:28.436 2321 info flutter.tools [        ] I/RongLog (25084): [ RongIMClient ] in Foreground
    10:43:28.436 2322 info flutter.tools [        ] E/RongLog (25084): [ RongIMClient ] rebind RongService: 
    DISCONNECTED

 
---

一、在初始化融云的时候 手机会弹出检测到多次异常，建议卸载。华为 9.1
二、就是上面的log了，我不管是用自己的appkey和token还是用你example里面的appkey和token都不能连接融云成功
