### ISSUE TITLE
初始化IM SDK -> 链接IM SDK提示appid 或 appkey 不能为空

### ISSUE THREAD

**Issue by x1245350223** [rongcloud/rongcloud-im-flutter-sdk#20]

**Comment by x1245350223** [comment]
appid or appkey can't be empty when enable MI push !

**Comment by x1245350223** [comment]
提示语如下：

**Comment by x1245350223** [comment]
提示语如下：
isSelfCertificate:false

appid or appkey can't be empty when enable MI push !

appid or appkey can't be empty when enable MEIZU push !

preferPushType:RONG; cachedPushType:RONG

enabledPushTypes:

isConfigChanged:false; cachedTypes:

register. type:RONG

enabledPushTypes:

mReconnectInterval 10

对程序的影响：

**Comment by x1245350223** [comment]
提示语如下：
isSelfCertificate:false

appid or appkey can't be empty when enable MI push !

appid or appkey can't be empty when enable MEIZU push !

preferPushType:RONG; cachedPushType:RONG

enabledPushTypes:

isConfigChanged:false; cachedTypes:

register. type:RONG

enabledPushTypes:

mReconnectInterval 10

对程序的影响：可以正常的发送消息，回调函数打印成功，但是无法接受消息！！！

**Comment by loginSin** [comment]
上面的 log 是小米，魅族推送相关的，和接收消息没有关系，无法收到消息的话是否正常写了接收消息的回调？项目的 READMe.md 里面写了如何写接收消息回调

**Comment by x1245350223** [comment]
> 上面的 log 是小米，魅族推送相关的，和接收消息没有关系，无法收到消息的话是否正常写了接收消息的回调？项目的 READMe.md 里面写了如何写接收消息回调

已解决，系后端人员生成token规则错误导致
