### ISSUE TITLE
希望RongIMClient的void方法改为Future<void>

### ISSUE THREAD

**Issue by DuYuanye** [rongcloud/rongcloud-im-flutter-sdk#201]
现有RongIMClient的方法都是采用回调的方式返回结果，对解耦和二次封装很不友好，
希望可以提供Future模式的返回

**Comment by ios-yifan** [comment]
您好，这个我们会在后续版本进行优化。

**Comment by ios-yifan** [comment]
您好，当前问题即将关闭，后续使用遇到任何问题可以在融云开发者后台提交工单，会有我们的技术人员进行及时处理。
