### ISSUE TITLE
502打不开怎么回事

### ISSUE THREAD

**Issue by beyondbkcy** [rongcloud/rongcloud-im-flutter-sdk#204]
![image](https://user-images.githubusercontent.com/25944695/130046862-cc9a2b16-db4a-43fd-be2f-5782269891cd.png)

**Comment by ios-yifan** [comment]
您好，现在还有遇到这个问题吗？

**Comment by ios-yifan** [comment]
您好，当前问题即将关闭，后续使用遇到任何问题可以在融云开发者后台提交工单，会有我们的技术人员进行及时处理。
