### ISSUE TITLE
图片没有压缩

### ISSUE THREAD

**Issue by elileo1** [rongcloud/rongcloud-im-flutter-sdk#205]
原生的sdk 图片是会压缩的，
flutter sdk 发现图片没有压缩，原图多大就发送多大

**Comment by ios-yifan** [comment]
您好，Flutter 层的图片最后调用的还是 SDK  的发送逻辑。您说的压缩是指？

**Comment by ios-yifan** [comment]
您好，当前问题即将关闭，后续使用遇到任何问题可以在融云开发者后台提交工单，会有我们的技术人员进行及时处理。
