### ISSUE TITLE
无法在Flutter2.5版本中使用（安装时报错）

### ISSUE THREAD

**Issue by langliu** [rongcloud/rongcloud-im-flutter-sdk#206]
* 本地 Flutter 版本：2.5

#### 报错信息

The plugin `rongcloud_im_plugin` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

#### 报错截图

![image](https://user-images.githubusercontent.com/18554111/132661485-6addffbe-9b60-47fa-b0c1-ef25c5d9ed57.png)

**Comment by ios-yifan** [comment]
当前问题 5.1.4+1  已修复
