### ISSUE TITLE
聊天页面，消息是逆序的呢？最后发的在上面。

### ISSUE THREAD

**Issue by ondev** [rongcloud/rongcloud-im-flutter-sdk#207]
与传统聊天页面不一样。应该是最后发的在最下面呀。

**Comment by ios-yifan** [comment]
当前提供的 demo 最后发的是显示在最下面的，UI 层仅提供参考，您可以根据您的业务逻辑来进行实现

**Comment by ios-yifan** [comment]
您好，当前问题即将关闭，后续使用遇到任何问题可以在融云开发者后台提交工单，会有我们的技术人员进行及时处理。
