### ISSUE TITLE
登录接口连接超时，无法登录

### ISSUE THREAD

**Issue by ZM0709** [rongcloud/rongcloud-im-flutter-sdk#208]
本地flutter版本2.5.2

iOS登录接口无法登录，连接超时，"http://api.sealtalk.im/user/login"

flutter: DioError [DioErrorType.DEFAULT]: SocketException: OS Error: Operation timed out, errno = 60, address = api.sealtalk.im, port = 52007

**Comment by ZM0709** [comment]
登陆接口换成这个就可以登陆了“https://api-sealtalk.rongcloud.cn/user/login”

**Comment by ios-yifan** [comment]
当前问题已修复。
