### ISSUE TITLE
其他端发送过来的RC:VcMsg, 我该如何在flutter读取该语音内容?

### ISSUE THREAD

**Issue by sherwin** [rongcloud/rongcloud-im-flutter-sdk#210]
*  rongcloud_im_plugin: ^5.1.6
* 发送语音是VoiceMessage的 RC:HQVCMsg

接收到安卓端的RC:VcMsg Message, 提示需要在originContentMap获取,   

 可是originContentMap里面只有
 `{duration: 4, isBurnAfterRead: false, burnDuration: 0}`

我该如何播放该语音消息呢?

**Comment by GP-Moon** [comment]
你好，RC:VcMsg 已经不推荐使用，Android和iOS请统一用RC:HQVCMsg类型的消息。

**Comment by sherwin** [comment]
你好, 是否有计划兼容旧版本的 RC:VcMsg 语音格式为 wav,  
希望能兼容.
