### ISSUE TITLE
IOS 打包报错

### ISSUE THREAD

**Issue by x1245350223** [rongcloud/rongcloud-im-flutter-sdk#22]
Unable to determine Swift version for the following pods:
- `audio_recorder` does not specify a Swift version and none of the targets (`Runner`)
integrating it have the `SWIFT_VERSION` attribute set. 

尝试在xcode的Runner对象新建一个任意名称的swift文件后，错误更新：
error: unable to attach DB: error: accessing build database "/User/max/Librar......": database is locked Possibly there are two concurrent builds running in the same filesystem location.

确认是引入 audio_recorder: ^1.0.1 依赖导致的错误！close #22

**Comment by x1245350223** [comment]
android录制语音报错：
Failed to handle method call
java.lang.RuntimeException: start failed.

**Comment by loginSin** [comment]
1 楼问题参考  https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/doc/iOS%20%E8%BF%90%E8%A1%8C%E6%AD%A5%E9%AA%A4%E8%AF%A6%E8%A7%A3.md

2 楼问题需要更多的 log 描述，audio_recorder 需要一些权限申请，是否正常申请？我们的项目已经用 audio_recorder 实现了语音的录制，你可以参考一下

**Comment by x1245350223** [comment]
> Unable to determine Swift version for the following pods:
> 
> * `audio_recorder` does not specify a Swift version and none of the targets (`Runner`)
>   integrating it have the `SWIFT_VERSION` attribute set.
> 
> 尝试在xcode的Runner对象新建一个任意名称的swift文件后，错误更新：
> error: unable to attach DB: error: accessing build database "/User/max/Librar......": database is locked Possibly there are two concurrent builds running in the same filesystem location.
> 
> 确认是引入 audio_recorder: ^1.0.1 依赖导致的错误！
