### ISSUE TITLE
Android打包出错

### ISSUE THREAD

**Issue by herghost000** [rongcloud/rongcloud-im-flutter-sdk#24]
环境：windows10
IDE：Android Studio 3.4
命令：flutter build apk
版本：rongcloud_im_plugin: ^0.9.5
描述：
1. 引入rongcloud_im_plugin前执行命令打包成功生成release apk
2. 引入rongcloud_im_plugin后使用右键Android文件夹-Flutter-Open Android Module in Android Studio，等待gradle完成后，点击Refactor-Migrate to Android，执行命令后
......
Note: there were 2 accesses to class members by means of introspection.
      You should consider explicitly keeping the mentioned class members
      (using '-keep' or '-keepclassmembers').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclassmember)
Warning: there were 241 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                     117.5s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleRelease failed with exit code 1
未成功生成release apk

**Comment by herghost000** [comment]
> 环境：windows10
> IDE：Android Studio 3.4
> 命令：flutter build apk
> 版本：rongcloud_im_plugin: ^0.9.5
> 描述：
> 
> 1. 引入rongcloud_im_plugin前执行命令打包成功生成release apk
> 2. 引入rongcloud_im_plugin后使用右键Android文件夹-Flutter-Open Android Module in Android Studio，等待gradle完成后，点击Refactor-Migrate to Android，执行命令后
>    ......
>    Note: there were 2 accesses to class members by means of introspection.
>    You should consider explicitly keeping the mentioned class members
>    (using '-keep' or '-keepclassmembers').
>    (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclassmember)
>    Warning: there were 241 unresolved references to classes or interfaces.
>    You may need to add missing library jars or update their versions.
>    If your code works fine without the missing classes, you can suppress
>    the warnings with '-dontwarn' options.
>    (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
>    Running Gradle task 'assembleRelease'...
>    Running Gradle task 'assembleRelease'... Done                     117.5s
> 
> The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
> See https://goo.gl/CP92wY for more information on the problem and how to fix it.
> 
> Gradle task assembleRelease failed with exit code 1
> 未成功生成release apk

在你example项目中使用的是如下打包方式，不会报错。
buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
           signingConfig signingConfigs.debug
        }
    }

当使用如下方式就会发生我的问题中的错误
    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
//            signingConfig signingConfigs.debug

            signingConfig signingConfigs.release
            minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

**Comment by loginSin** [comment]
`The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.`
看上去像是 AndroidX 的问题，集成 我们的  SDK 之后 Android 项目是否可以正常运行？

**Comment by herghost000** [comment]
> `The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app. See https://goo.gl/CP92wY for more information on the problem and how to fix it.`
> 看上去像是 AndroidX 的问题，集成 我们的 SDK 之后 Android 项目是否可以正常运行？

可以运行，不能打包，我找到原因了
useProguard true
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

混淆后打包就会出现我的问题

**Comment by herghost000** [comment]
> `The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app. See https://goo.gl/CP92wY for more information on the problem and how to fix it.`
> 看上去像是 AndroidX 的问题，集成 我们的 SDK 之后 Android 项目是否可以正常运行？



> `The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app. See https://goo.gl/CP92wY for more information on the problem and how to fix it.`
> 看上去像是 AndroidX 的问题，集成 我们的 SDK 之后 Android 项目是否可以正常运行？

example打包后运行闪退
华为手机
EMUI 9.0.0
Android 9
