### ISSUE TITLE
getConversationNotificationStatus invokeMethod 错误的使用了SetConversationNotificationStatus

### ISSUE THREAD

**Issue by qiuqiu0113** [rongcloud/rongcloud-im-flutter-sdk#27]
源码如下：
static void getConversationNotificationStatus(int conversation, String targetId, Function(int status, int code) finished) async {
    Map map = {
      "conversation": conversation,
      "targetId": targetId
    };
    Map statusMap = await _channel.invokeMethod(RCMethodKey.SetConversationNotificationStatus, map);
    if (finished != null) {
      finished(statusMap["status"], statusMap["code"]);
    }
  }

麻烦改下～～

**Comment by loginSin** [comment]
好的，这边处理一下

**Comment by loginSin** [comment]
问题已在 master 修复，最迟本周五下午发布新版本

**Comment by loginSin** [comment]
问题已修复，最新版本 0.9.7

**Comment by qiuqiu0113** [comment]
> 问题已修复，最新版本 0.9.7

不好使～～回调不走～～

**Comment by loginSin** [comment]
Android 还是 iOS 不好使？

**Comment by loginSin** [comment]
确实有问题，Flutter 传递的参数和 iOS/Android 接收的参数不一样，导致 iOS/Android 无法正常解析到会话类型，这边处理一下

**Comment by loginSin** [comment]
紧急更新了一版，0.9.7+1

**Comment by qiuqiu0113** [comment]
> 紧急更新了一版，0.9.7+1

还有一个小问题啊～～
返回的 status 永远是1 code永远是0  不知道是不是block了～
set的时候。。也永远返回status 1 code 0

**Comment by qiuqiu0113** [comment]
> 紧急更新了一版，0.9.7+1

有回调了
但是返回值 status 永远是1  code 永远是0 不知道有没有block

另外 set函数好用了 日志上看 isblock 传递的是正确的 0/1 但是返回的stuas 也永远是1 code 永远是0

**Comment by qiuqiu0113** [comment]
iOS哈

**Comment by loginSin** [comment]
处理了，新版 0.9.7+2
