### ISSUE TITLE
setConversationToTop isTop 没有放入参数isTop  放了两个targetId。。。

### ISSUE THREAD

**Issue by qiuqiu0113** [rongcloud/rongcloud-im-flutter-sdk#28]
源码如下：
static void setConversationToTop(int conversationType, String targetId, bool isTop, Function(bool status, int code) finished) async {
    Map map = {
      "conversationType": conversationType,
      "targetId": targetId,
      "targetId": targetId
    };
    Map conversationMap = await _channel.invokeMethod(RCMethodKey.SetConversationToTop, map);
    if (finished != null) {
      finished(conversationMap["status"], conversationMap["code"]);
    }
  }

**Comment by loginSin** [comment]
好的，这边处理一下

**Comment by loginSin** [comment]
问题已在 master 修复，最迟本周五下午发布新版本

**Comment by loginSin** [comment]
问题已修复，最新版本 0.9.7

**Comment by qiuqiu0113** [comment]
> 问题已修复，最新版本 0.9.7

好使了～
