### ISSUE TITLE
发送消息报错

### ISSUE THREAD

**Issue by dukezhao** [rongcloud/rongcloud-im-flutter-sdk#30]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息，v1.7.8+hotfix.4 macOs 10.14.5 18f132
* 异常设备是 Android，小米 max 2 android 7.1
* 所调用的是什么 API 或者说是什么功能，发送消息功能
* 完整的报错信息或者问题描述，
* 提供问题发生时必要的日志，并以 txt 形式上传
E/flutter (23690): #43     ComponentE
I/flutter (23690): scroller 最大值 oldWidget0.0
I/[RC-Flutter-IM] Android (23690): sendMessage start param:{targetId=sealTalk, objectName=RC:TxtMsg, pushData=, conversationType=null, content={"content":"晕晕乎乎还回家","extra":null}, pushContent=}
E/MethodChannel#rongcloud_im_plugin(23690): Failed to handle method call
E/MethodChannel#rongcloud_im_plugin(23690): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/MethodChannel#rongcloud_im_plugin(23690): 	at com.example.rongcloud_im_plugin.RCIMFlutterWrapper.sendMessage(RCIMFlutterWrapper.java:306)
E/MethodChannel#rongcloud_im_plugin(23690): 	at com.example.rongcloud_im_plugin.RCIMFlutterWrapper.onFlutterMethodCall(RCIMFlutterWrapper.java:86)
E/MethodChannel#rongcloud_im_plugin(23690): 	at com.example.rongcloud_im_plugin.RongcloudImPlugin.onMethodCall(RongcloudImPlugin.java:21)
E/MethodChannel#rongcloud_im_plugin(23690): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#rongcloud_im_plugin(23690): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#rongcloud_im_plugin(23690): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#rongcloud_im_plugin(23690): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#rongcloud_im_plugin(23690): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#rongcloud_im_plugin(23690): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#rongcloud_im_plugin(23690): 	at android.app.ActivityThread.main(ActivityThread.java:6388)
E/MethodChannel#rongcloud_im_plugin(23690): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#rongcloud_im_plugin(23690): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:930)
E/MethodChannel#rongcloud_im_plugin(23690): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)
E/flutter (23690): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null)
E/flutter (23690): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (23690): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (23690): <asynchronous suspension>
E/flutter (23690): #2      RongcloudImPlugin.sendMessageCarriesPush (package:rongcloud_im_plugin/src/rong_im_plugin.dart:123:36)
E/flutter (23690): <asynchronous suspension>
E/flutter (23690): #3      RongcloudImPlugin.sendMessage (package:rongcloud_im_plugin/src/rong_im_plugin.dart:89:12)
E/flutter (23690): <asynchronous suspension>
E/flutter (23690): #4      _ConversationPageState.willSendText (package:taiim/page/conversation/conversation_page.dart:311:33)
E/flutter (23690): <asynchronous suspension>
E/flutter (23690): #5      _BottomInputBarState._clickSendMessage (package:taiim/page/item/bottom_input_bar.dart:58:21)
E/flutter (23690): #6      EditableTextState._finalizeEditing (package:flutter/src/widgets/editable_text.dart:1087:14)
E/flutter (23690): #7      EditableTextState.performAction (package:flutter/src/widgets/editable_text.dart:993:9)
E/flutter (23690): #8      _TextInputClientHandler._handleTextInputInvocation (package:flutter/src/services/text_input.dart:746:36)
E/flutter (23690): <asynchronous suspension>
E/flutter (23690): #9      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:397:55)
E/flutter (23690): <asynchronous suspension>
E/flutter (23690): #10     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:365:54)
E/flutter (23690): #11     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binary_messenger.dart:110:33)
E/flutter (23690): <asynchronous suspension>
E/flutter (23690): #12     _invoke3.<anonymous closure> (dart:ui/hooks.dart:280:15)
E/flutter (23690): #13     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (23690): #14     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (23690): #15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (23690): #16     _invoke3 (dart:ui/hooks.dart:279:10)
E/flutter (23690): #17     _dispatchPlatformMessage (dart:ui/hooks.dart:141:5)
E/flutter (23690): 
I/flutter (23690): scroller 最大值 oldWidget0.0
I/[RC:L-ping-S](23690): {"ptid":"23926-23634","interval":15000,"enabled":"polling"}
D/[RC:P-reason-C](23690): {"ptid":"23926-23634","action":"env_changed","reason":"105"}
I/[RC:L-ping-S](23690): {"ptid":"23926-23634","interval":15000,"enabled":"polling"}
D/[RC:P-reason-C](23690): {"ptid":"23926-23634","action":"env_changed","reason":"105"}
I/[RC:L-ping-S](23690): {"ptid":"23926-23634","interval":15000,"enabled":"polling"}
D/[RC:P-reason-C](23690): {"ptid":"23926-23634","action":"env_changed","reason":"105"}

文档链接 https://github.com/rongcloud/rongcloud-im-flutter-sdk/tree/dev/doc
文档持续更新中……

**Comment by loginSin** [comment]
{targetId=sealTalk, objectName=RC:TxtMsg, pushData=, conversationType=null, content={"content":"晕晕乎乎还回家","extra":null}, pushContent=}

这行 log 中没有传具体的回话类型，所以说发送失败了，具体可以参见 RCConversationType 的枚举值
