### ISSUE TITLE
获取历史消息的相关问题

### ISSUE THREAD

**Issue by speanut-land** [rongcloud/rongcloud-im-flutter-sdk#31]
询问作者获取本地历史消息或者是远端的历史消息时，不支持分页吗？ 就比如先请求20条数据，当滚动到最大值时，又获取20条数据，看了很久的文档与example及issues没有相关的，都只有一次性获得前多少条数据，并不是分页的，看了RN的融云IM是有相关的接口的，问问flutter 的SDK能够集成吗？

询问一下作者，看到融云IM的插件有set用户信息(头像 名字 )但是没有get用户信息 问问用户信息是得自己来维护的吗?

**Comment by loginSin** [comment]
static Future<List> getHistoryMessage(int conversationType, String targetId, int messageId, int count)
要求传递一个消息 id 和 个数，首次进入传入0 ，后续用户拉取传对应的 messageid 就行

**Comment by speanut-land** [comment]
> static Future getHistoryMessage(int conversationType, String targetId, int messageId, int count)
> 要求传递一个消息 id 和 个数，首次进入传入0 ，后续用户拉取传对应的 messageid 就行

对于查询历史记录还是不懂🤔️ ， messageId是看接口是<本地数据库的自增 id>,所以我现在理解你这句话的意思就是  
>前面两个参数不会变，后面的count仅仅是请求数量正常传入一个常量就可以，所以只需要将messageId变成变量依次增加？ 还是很困惑，作者大大能否直接写一个列子呢？ 还有作者大大忽略但那个用户信息问题emmmm....

**Comment by speanut-land** [comment]
> static Future getHistoryMessage(int conversationType, String targetId, int messageId, int count)
> 要求传递一个消息 id 和 个数，首次进入传入0 ，后续用户拉取传对应的 messageid 就行

询问作者有解决的方案吗emmmm

**Comment by speanut-land** [comment]
询问作者什么时间能够更新插件 ，及问问作者大佬，如何实现下拉加载而不会导致直接跳转到第一条呢？就是listview 设置reverse为true后 会导致向数组加入数据，更新视图后直接到底部 而不是刷新时的位置

**Comment by learyR** [comment]
急急急  同样的问题
咋个解决啊
