### ISSUE TITLE
能够新增一个根据id获取conversation的字段

### ISSUE THREAD

**Issue by qiuqiu0113** [rongcloud/rongcloud-im-flutter-sdk#32]
如果不从im的最近联系人页面进入聊天页面，无法方便的根据id获取conversation以及相关信息。

ps：
setConversationToTop 能够增加对应的getConversationToTop

**Comment by loginSin** [comment]
SDK 确定一个会话必须是 conversationType 和 targetId 才能唯一确定一个会话，是需要增加根据 会话类型和 targetId 找单个会话的接口吗？
getConversationToTop 接口 Android 没有实现，所以 Flutter 就没有该接口，可以通过 getConversationList 获取所有回话，每个会话有 isTop 字段，表明该会话是否置顶

**Comment by qiuqiu0113** [comment]
> SDK 确定一个会话必须是 conversationType 和 targetId 才能唯一确定一个会话，是需要增加根据 会话类型和 targetId 找单个会话的接口吗？
> getConversationToTop 接口 Android 没有实现，所以 Flutter 就没有该接口，可以通过 getConversationList 获取所有回话，每个会话有 isTop 字段，表明该会话是否置顶

是的
