### ISSUE TITLE
无法运行？一直卡在到pod install...这一步

### ISSUE THREAD

**Issue by MuZiLee** [rongcloud/rongcloud-im-flutter-sdk#33]
我添加完rongcloud_im_plugin: ^0.9.7+2之后，在程序启动中只是添加了RongcloudImPlugin.init(“appkey”);这个方法，然后运行。就一直卡在pod install .....这一步。开始我还以为需要下载iOS和Andorid的SDK，但是我等了一个通宵都没有pod完。请问是什么问题。pod 的sources是国内源。

![image](https://user-images.githubusercontent.com/7467318/65143901-a9a25780-da48-11e9-9ed6-a10db42deec9.png)

**Comment by loginSin** [comment]
这个可能是 Flutter 的问题，建议可以手动更新 pod ，可以参考
https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/doc/iOS%20%E8%BF%90%E8%A1%8C%E6%AD%A5%E9%AA%A4%E8%AF%A6%E8%A7%A3.md#%E4%B8%8B%E8%BD%BD-ios-%E4%BE%9D%E8%B5%96%E5%8C%85

**Comment by MuZiLee** [comment]
@loginSin 非常感谢，我看看。希望能解决我的问题。

**Comment by MuZiLee** [comment]
实在太麻烦了
