### ISSUE TITLE
播放语音卡死，flutter_sound报错

### ISSUE THREAD

**Issue by tianyu704** [rongcloud/rongcloud-im-flutter-sdk#34]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
*  Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G84, locale zh-Hans-CN)
* Android，华为P30Pro,EMUI 9.1.0, android 9
* flutterSound.startPlayer(url)
* 发送语音后，播放时卡死，稍后会报错如下
* 
E/FlutterSoundPlugin(23653): startPlayer() exception
E/flutter (23653): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Exception: PlatformException(ERR_UNKNOWN, ERR_UNKNOWN, Prepare failed.: status=0x1)
E/flutter (23653): #0      FlutterSound.startPlayer (package:flutter_sound/flutter_sound.dart:178:7)
E/flutter (23653): <asynchronous suspension>
E/flutter (23653): #1      MediaUtil.startPlayAudio (package:rongcloud_im_plugin_example/im/util/media_util.dart:94:18)
E/flutter (23653): #2      _ConversationPageState.didTapMessageItem (package:rongcloud_im_plugin_example/im/pages/conversation_page.dart:279:26)
E/flutter (23653): #3      _ConversationItemState.__onTapedMesssage (package:rongcloud_im_plugin_example/im/pages/item/conversation_item.dart:117:16)
E/flutter (23653): #4      _ConversationItemState.buildMessageWidget.<anonymous closure> (package:rongcloud_im_plugin_example/im/pages/item/conversation_item.dart:154:17)
E/flutter (23653): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (23653): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (23653): #7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
E/flutter (23653): #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (23653): #9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (23653): #10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (23653): #11     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (23653): #12     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (23653): #13     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (23653): #14     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (23653): #15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (23653): #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (23653): #17     _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter (23653): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)

文档链接 https://github.com/rongcloud/rongcloud-im-flutter-sdk/tree/dev/doc
文档持续更新中……

**Comment by loginSin** [comment]
使用 该项目中的  demo 能否复现上面提到的问题，语音播放出现异常，常见的问题是文件头
Android 的话本地文件需要加 "file://" 文件头，而 iOS 本地文件不能加 “file://” 文件头

**Comment by tianyu704** [comment]
@loginSin 播放的是网络地址，不是本地的文件，是消息中返回的语音地址

**Comment by speanut-land** [comment]
@loginSin  这里也遇到相同的问题 ，之前手机是andriod8 然后升级到andriod9 由于google在框架上进行了安全性的升级，无法直接访问http资源，需要升级https或者在 androidmanifest.xml 中配置域名清单。

**Comment by speanut-land** [comment]
@loginSin 问问这里该如何解决呢

**Comment by CNHarrySun** [comment]
请问在清单文件配置之后还有问题吗？
