### ISSUE TITLE
example無法運行

### ISSUE THREAD

**Issue by huscarter** [rongcloud/rongcloud-im-flutter-sdk#35]
本地 Flutter 版本：1.9.1+hotfix.2
异常设备是： Android，錘子手機OC105
安裝啓動apk崩潰：
/com.example.rongcloud_im_plugin_example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.rongcloud_im_plugin_example, PID: 11832
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.rongcloud_im_plugin_example-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.rongcloud_im_plugin_example-1/lib/arm, /data/app/com.example.rongcloud_im_plugin_example-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"

**Comment by huscarter** [comment]
后台按照 doc/Android运行步骤详解运行OK。

**Comment by leejunhui** [comment]
@huscarter 我也是用的锤子手机 OS105型号，可以运行Example工程，但是一运行就闪退，而且没有打印报错信息，在模拟器上运行又会报不支持x86的错误，好方~
