### ISSUE TITLE
android,当应用处于后台非活动时，无法接收消息

### ISSUE THREAD

**Issue by snglw07** [rongcloud/rongcloud-im-flutter-sdk#4]
android,当应用处于后台非活动时，无法接收消息

**Comment by loginSin** [comment]
可否提供完整的 log？

**Comment by yongzhengqi** [comment]
看这[issue 5](https://github.com/rongcloud/rongcloud-im-flutter-sdk/issues/5)，感觉是插件还没有实现这个功能？ @loginSin

**Comment by huscarter** [comment]
iOS、Android关闭应用后都无法接收到消息，这个问题很鸡肋

**Comment by CNHarrySun** [comment]
你好，demo 中 0.9.5 版本已经加入了本地通知的实现。
