### ISSUE TITLE
当应用被杀死之后无法接收到融云消息

### ISSUE THREAD

**Issue by huscarter** [rongcloud/rongcloud-im-flutter-sdk#42]
本地 Flutter 版本：1.9.1
异常设备： iphone6s(iOS12.4.1)（貌似Android设备也一样）
问题：当app杀死（不是退出到后台）后，发送的融云消息接收不到，包括单聊和推送消息。

**Comment by loginSin** [comment]
Flutter 在 Android 平台的推送使用的还是 Android 原生的功能，可以参考我们官方 Android 推送文档
https://docs.rongcloud.cn/im/push/android/summary/
