### ISSUE TITLE
希望能提供类似kit的关于ui的Widget。目前sdk是否支持发送文件啊，只知道支持 发送图片和语音

### ISSUE THREAD

**Issue by jicg** [rongcloud/rongcloud-im-flutter-sdk#43]
希望能提供类似kit的关于ui的Widget。目前sdk是否支持发送文件啊，只知道支持 发送图片和语音

**Comment by loginSin** [comment]
整个项目直接运行的话是已经写好了消息发送和展示的 UI ，目前不支持文件消息

**Comment by jicg** [comment]
谢谢，希望能尽快支持文件发送。原生的IMKit 是支持发送文件。
