### ISSUE TITLE
获取所有未读消息的接口返回的数据不准确

### ISSUE THREAD

**Issue by qiuqiu0113** [rongcloud/rongcloud-im-flutter-sdk#44]
RongcloudImPlugin.getUnreadCountConversationTypeList([RCConversationType.Private], false, (count,code){
      print("------unread= $count ------ code= $code");
    });

count 第一次请求的时候，有时候会返回0，但是实际数值并不是0.
再次调用此函数的时候就没有问题了。

code 返回的是0

**Comment by CNHarrySun** [comment]
您看下是什么时候调用的，需要在 connect 成功之后调用。
