### ISSUE TITLE
网络不太好的情况下消息发送失败

### ISSUE THREAD

**Issue by qiuqiu0113** [rongcloud/rongcloud-im-flutter-sdk#46]
网络不太好的情况下，ios和android 都会出现消息发送失败的情况。
其中ios更严重一下，发送语音比发送文字严重一些。

当前网络虽然比较不好，但是也没有那么差。
正常浏览网页，聊微信什么的都没问题。按理说不该出现发送失败的问题。

怀疑是不是连接服务器超时的太快了？还是什么原因导致的？

麻烦您处理下。

**Comment by loginSin** [comment]
如果可以请提供一下完整的 log，只有文字描述没办法准确的定位问题
