### ISSUE TITLE
getConversationList 退出a账号退出app，打开app登录b账号成功之前 getConversationList 获取的是a账号的聊天记录

### ISSUE THREAD

**Issue by qiuqiu0113** [rongcloud/rongcloud-im-flutter-sdk#49]
getConversationList  disconnect a账号退出app，打开app登录connect b账号成功之前 getConversationList 获取的是a账号的聊天记录。

希望能够判断是否是connect状态，是connect状态才能够正常获取到数据。否则不返回数据。

感谢。

**Comment by electronicZ** [comment]
同问

**Comment by loginSin** [comment]
可否提供一下完整的 log？Flutter SDK 基于 iOS/Android  SDK 的，是不会有这类的问题，在 SDK 尚未连接成功时尚不知道用户 id，是无法打开对应的消息数据库的，除非本次连接使用的 token 和上次是同一个 token，所以猜测有没有可能是 a disconnect 然后在打开 APP 的 时候 a  connect 了然后 b 又 connect 了
具体的分析必须得要完整的 log
