### ISSUE TITLE
消息推送功能是否完善？

### ISSUE THREAD

**Issue by 0xBinX** [rongcloud/rongcloud-im-flutter-sdk#5]
1.APP后台运行 
[ RongNotificationManager ] No popup notification cause of the sender name is null, please set UserInfoProvider
2.怎样处理接收到的推送消息

**Comment by 0xBinX** [comment]
已解决，该插件还尚未完成

**Comment by yongzhengqi** [comment]
请问现在插件完成了吗？在小米和IOS上测试了0.9.2版本，似乎还是没有完成。
