### ISSUE TITLE
群聊 的头像，没法区分用户和群聊

### ISSUE THREAD

**Issue by jicg** [rongcloud/rongcloud-im-flutter-sdk#50]
获取后台用户头像的时候，需要区分是用户还是群组。因此仅仅传入userId 是不够的。
希望能调整下example部分的代码，方便能区分用户还是群组

下面是个人的调整example部分代码的示例。

修改：im/util/user_info_datesource.dart，添加参数 conversationType
```dart
class UserInfoDataSource {
...
  static UserInfo getUserInfo(String userId,
      [int conversationType=RCConversationType.Private]
      ) {
   ...
  }
}
```
修改：rongmi/im/pages/item/conversation_list_item.dart，调用getUserInfo时传入 聊天类型
```dart
_ConversationListItemState(ConversationListItemDelegate delegate,Conversation con) {
    ...
  // 传入聊天类型
    this.user = UserInfoDataSource.getUserInfo(con.targetId,con.conversationType);
  }
```
修改：im/pages/conversation_page.dart，调用getUserInfo时传入 聊天类型
```dart 
 ...

class _ConversationPageState extends State<ConversationPage> implements ConversationItemDelegate,BottomInputBarDelegate {
...
 // 传入聊天类型 
this.user = UserInfoDataSource.getUserInfo(targetId,conversationType);
...
```

**Comment by sm9i** [comment]
插件有获取 user的地方吗？

**Comment by jicg** [comment]
有，需要自己实现 im/util/user_info_datesource.dart

**Comment by sm9i** [comment]
> 有，需要自己实现 im/util/user_info_datesource.dart

我用的是pub的依赖，没有的啊？你用的是git的吗

**Comment by sm9i** [comment]
> 有，需要自己实现 im/util/user_info_datesource.dart

我看了git的代码 没有那个类啊

**Comment by jicg** [comment]
你需要 把example部分代码复制到你的项目里面，自己改

**Comment by sm9i** [comment]
> 你需要 把example部分代码复制到你的项目里面，自己改

那这样麻烦了。不如请求自己的服务器我看 原生代码android 有 user信息但是没有返回到flutter  但是ios没有。。

**Comment by loginSin** [comment]
https://github.com/rongcloud/rongcloud-im-flutter-sdk/commit/59bba7c834ec51550420fe7f707f53de1956456d

可以参考这一次提交，直接如果是群组的，那么名称变成 群组* 格式，通过名称直接区分是单聊还是群聊


以下是建议的用户/群组信息整个处理流程

会话列表和消息列表的用户相关信息 Widget 简写成 Widget
1.Widget 向 UserInfoDataSource 索要用户/群组信息
2.UserInfoDataSource 检查是否有该用户/群组信息
3.如果有信息，那么返回用户信息给 Widget 展示
4.如果 UserInfoDataSource 本地没有用户信息，那么需要向 APP 服务获取，获取完成之后，将用户/群组信息传给 widget，UserInfoDataSource 同时将用户/群组信息保存，方便之后的获取

**Comment by jicg** [comment]
好的，谢谢 回复
