### ISSUE TITLE
ios 融云flutter外部包 初始化 bulid后出现报错

### ISSUE THREAD

**Issue by qz19960827** [rongcloud/rongcloud-im-flutter-sdk#51]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.8.3, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
[✓] Android Studio (version 3.4)
[✓] Connected device (2 available)
报错：
 <module-includes>:1:1: warning: umbrella header for module 'RongIMLib' does not include header 'RCBurnMessageService.h' [-Wincomplete-umbrella]
    #import "Headers/RongIMLib.h"
    ^
    1 warning generated.
    1 warning generated.
    /Users/zhuhong/.pub-cache/hosted/pub.flutter-io.cn/rongcloud_im_plugin-0.9.9/ios/Classes/RCIMFlutterWrapper.m:209:25: warning: unused variable 'user' [-Wunused-variable]
                RCUserInfo *user = [[RCUserInfo alloc] initWithUserId:userId name:name portrait:portraitUrl];
                            ^
    /Users/zhuhong/.pub-cache/hosted/pub.flutter-io.cn/rongcloud_im_plugin-0.9.9/ios/Classes/RCIMFlutterWrapper.m:305:20: error: unknown receiver 'RCHQVoiceMessage'; did you mean 'RCVoiceMessage'?
            content = [RCHQVoiceMessage messageWithPath:localPath duration:duration];
                       ^~~~~~~~~~~~~~~~
                       RCVoiceMessage
    In module 'RongIMLib' imported from /Users/zhuhong/.pub-cache/hosted/pub.flutter-io.cn/rongcloud_im_plugin-0.9.9/ios/Classes/RCFlutterMessageFactory.h:9:
    /Users/zhuhong/Documents/whova/ios/Pods/RongCloudIM/RongCloudIM/RongIMLib.framework/Headers/RCVoiceMessage.h:25:12: note: 'RCVoiceMessage' declared here
    @interface RCVoiceMessage : RCMessageContent <NSCoding>等错误
做了基础的初始化后，就全面报错

**Comment by qz19960827** [comment]
麻烦大神们了，

**Comment by loginSin** [comment]
进入 example/ios 目录，执行 `pod repo update` 和 `pod update` 命令，手动更新 SDK 版本，该过程会花费较长的时间
该过程可能是因为本地 iOS SDK 版本比较旧，尚未支持 RCHQVoiceMessage
