### ISSUE TITLE
打开app后闪退： MainActivity does not exist.

### ISSUE THREAD

**Issue by kelly54312** [rongcloud/rongcloud-im-flutter-sdk#52]
打开app后闪退：
Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.rongcloud_im_plugin_example/.MainActivity (has extras) }
Error type 3
Error: Activity class {com.example.rongcloud_im_plugin_example/com.example.rongcloud_im_plugin_example.MainActivity} does not exist.

**Comment by loginSin** [comment]
直接使用的该项目的源码，没有做任何改动，直接运行的 Android 就崩溃是吗？可否提供更多的信息，如 具体机型，系统，复现问题的步骤等，我们尝试用同样的设备和步骤复现一下该问题

**Comment by kelly54312** [comment]
我两个手机，一个vivo，一个oppo都闪退

**Comment by loginSin** [comment]
1.今天尝试了 小米 5 和 OPPO R15，是可以正常运行的
2.你那边出现问题的话，直接运行的 github 仓库的源码还是对源码有所改动？
3.如果用了没有改动的源码出现了问题，那么请详细描述一下复现的步骤和具体设备机型，这边好尝试复现

这边验证的方式是用 Android studio 打开 example/android 目录，直接运行该项目

**Comment by kelly54312** [comment]
我是用flutter 工程打开，连着手机 运行，安装完成后闪退

**Comment by CNHarrySun** [comment]
您重新下载下 rongcloud-im-flutter-sdk，然后进入到 rongcloud-im-flutter-sdk/example 中执行 flutter run 看下。
