### ISSUE TITLE
关于example 推送的问题 

### ISSUE THREAD

**Issue by sm9i** [rongcloud/rongcloud-im-flutter-sdk#53]
https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/example/ios/Runner/AppDelegate.m#L68

这里不需要 类似 https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/example/ios/Runner/AppDelegate.m#L37  这样的操作吗？不延迟也不点shared？  原谅我不会 ios  还有就是 为什么要点shared 而不是 sharedWrapper？

**Comment by loginSin** [comment]
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
该方法是在 APP 活跃状态下，收到远程推送才会触发，那么此时就不需要做延时，上面提到的延时是因为 Flutter 和 APP 启动是同时进行的，有可能 APP 启动了，收到了推送数据 Flutter 引擎还未初始化，无法拿到数据，所以才做的延时
shared还是 sharedWrapper 的问题，使用的是 Swift 吗？OC 和 Swift 对于单例类的语法是不一样的，能正常运行就行
