### ISSUE TITLE
第三方推送配置呢？

### ISSUE THREAD

**Issue by sm9i** [rongcloud/rongcloud-im-flutter-sdk#54]
第三方推送怎么不加诶？还得自己魔改插件？

**Comment by loginSin** [comment]
第三方推送您是指类似小米华为的推送吗？该 Flutter  SDK 本质上使用了融云 Android & iOS  IMLib  SDK ，推送的话，跟原生 SDK 的处理逻辑一样，可以参考官方文档
[Android Push](https://docs.rongcloud.cn/im/push/android/summary/)
[iOS Push](https://docs.rongcloud.cn/im/push/ios/apns-mechanism/)
[Flutter 本地通知的实现](https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/doc/%E6%9C%AC%E5%9C%B0%E9%80%9A%E7%9F%A5%E4%B8%8E%E8%BF%9C%E7%A8%8B%E6%8E%A8%E9%80%81%E7%9A%84%E5%AE%9E%E7%8E%B0.md)

**Comment by sm9i** [comment]
是。。但是 你们必须集成啊。。PushConfig 必须改插件啊

**Comment by CNHarrySun** [comment]
远程推送已经在排期中，后续会进行开发。

**Comment by CNHarrySun** [comment]
远程推送实现可以先参考这个文档：https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/doc/%E6%9C%AC%E5%9C%B0%E9%80%9A%E7%9F%A5%E4%B8%8E%E8%BF%9C%E7%A8%8B%E6%8E%A8%E9%80%81%E7%9A%84%E5%AE%9E%E7%8E%B0.md
