### ISSUE TITLE
flutter 获取最近联系人 ，用获取会话列表接口RongcloudImPlugin.getConversationList，有时不准确

### ISSUE THREAD

**Issue by kelly54312** [rongcloud/rongcloud-im-flutter-sdk#55]
flutter 获取最近联系人 ，用获取会话列表接口RongcloudImPlugin.getConversationList，有时不准确。 有时不能获取完全的名单，有些对话没有获取。 例如和一个人对话，然后退出app，再次登录时，调用RongcloudImPlugin.getConversationList，有时能获取，有时获取不到：返回null。 请给看一下，谢谢

**Comment by CNHarrySun** [comment]
必须在 connect 成功之后再获取。
