### ISSUE TITLE
Conversation 的 latestMessageContent属性，类型错误

### ISSUE THREAD

**Issue by mjl0602** [rongcloud/rongcloud-im-flutter-sdk#57]
标记为`MessageContent`类实际上获取到的是`TextMessage`类

**Comment by loginSin** [comment]
MessageContent 是所有消息的父类，文本消息图片消息语音消息小视频消息等均是其子类

**Comment by mjl0602** [comment]
已了解，但此处如此处理会导致无意义的as转换，且不能得到ide的有效提示，也无法快速查看子类的情况。

建议，能否添加一系列getter，直接获取对应类型的content，类型错误时返回null，方便在明知消息类型时快速取值，且能获得友好的提示。

**Comment by CNHarrySun** [comment]
OK，感谢建议，我们后面看下如何优化。

**Comment by sherwin** [comment]
2021.09.29 至今未解决

**Comment by ios-yifan** [comment]
您好，MessageContent 是 SDK 内置消息和所有开发者自定义消息的父类，SDK 是无法具体确认 content 类型的，无法去限制具体的类型，这部分内容还是 需要在业务上进行处理。
