### ISSUE TITLE
插件没有提供第三方推送配置方法

### ISSUE THREAD

**Issue by huscarter** [rongcloud/rongcloud-im-flutter-sdk#58]
原生adk提供了下面的推送配置方法：
PushConfig config = new PushConfig.Builder()
                .enableMiPush() 
                .enableOppoPush() 
                .enableHWPush()
                .enableMeiZuPush()
                .enableVivoPush() 
                .build();
        RongPushClient.setPushConfig(config);
flutter 插件没有找到。

**Comment by yanxiame** [comment]
可以自己去 RongcloudImPlugin 中拓展。
