### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by leielyq** [rongcloud/rongcloud-im-flutter-sdk#62]
Xcode's output:
↳
    warning: The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.2.99. (in target 'RongCloudIM')
    /Users/mac/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/rongcloud_im_plugin-1.0.2/ios/Classes/RCFlutterMessageFactory.m:69:32: error: unknown receiver 'RCMediaMessageContent'; did you mean 'RCMessageContent'?
        if([content isKindOfClass:[RCMediaMessageContent class]]) {
                                   ^~~~~~~~~~~~~~~~~~~~~
                                   RCMessageContent
    In file included from /Users/mac/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/rongcloud_im_plugin-1.0.2/ios/Classes/RCFlutterMessageFactory.m:8:
    In file included from /Users/mac/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/rongcloud_im_plugin-1.0.2/ios/Classes/RCFlutterMessageFactory.h:9:
    In file included from /Users/mac/Documents/Android/TCHAT/IM_GOOGLE 2/flutter_module_test/ios/Pods/RongCloudIM/RongCloudIM/RongIMLib.framework/Headers/RongIMLib.h:22:
    In file included from /Users/mac/Documents/Android/TCHAT/IM_GOOGLE 2/flutter_module_test/ios/Pods/RongCloudIM/RongCloudIM/RongIMLib.framework/Headers/RCIMClient.h:19:
    In file included from /Users/mac/Documents/Android/TCHAT/IM_GOOGLE 2/flutter_module_test/ios/Pods/RongCloudIM/RongCloudIM/RongIMLib.framework/Headers/RCConversation.h:13:
    /Users/mac/Documents/Android/TCHAT/IM_GOOGLE 2/flutter_module_test/ios/Pods/RongCloudIM/RongCloudIM/RongIMLib.framework/Headers/RCMessageContent.h:116:12: note: 'RCMessageContent' declared here
    @interface RCMessageContent
               ^
    /Users/mac/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/rongcloud_im_plugin-1.0.2/ios/Classes/RCFlutterMessageFactory.m:70:9: error: unknown type name 'RCMediaMessageContent'; did you mean 'RCMessageContent'?
            RCMediaMessageContent *msg = (RCMediaMessageContent *)content;
            ^~~~~~~~~~~~~~~~~~~~~
            RCMessageContent
    In file included from /Users/mac/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/rongcloud_im_plugin-1.0.2/ios/Classes/RCFlutterMessageFactory.m:8:
    In file included from /Users/mac/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/rongcloud_im_plugin-1.0.2/ios/Classes/RCFlutterMessageFactory.h:9:

**Comment by loginSin** [comment]
看 log 是您本地的 iOS SDK 版本较低，您可以在 podfile 目录执行 pod repo update 和 pod update 命令更新一下 pod

**Comment by leielyq** [comment]
> 看 log 是您本地的 iOS SDK 版本较低，您可以在 podfile 目录执行 pod repo update 和 pod update 命令更新一下 pod

好的，请问推送支持的吗
