### ISSUE TITLE
历史消息分页获取

### ISSUE THREAD

**Issue by leielyq** [rongcloud/rongcloud-im-flutter-sdk#63]
希望能加入这个接口，谢谢

**Comment by CNHarrySun** [comment]
您好，请问您说的是这个接口吗？
![image](https://user-images.githubusercontent.com/16249166/76599207-7811d100-653f-11ea-84b7-1f2819ba56c7.png)

**Comment by leielyq** [comment]
对  这个问题提的比较早。现在已经可以了
