### ISSUE TITLE
编译后的apk无法在特定安卓机型上运行

### ISSUE THREAD

**Issue by MaChengtianjiang** [rongcloud/rongcloud-im-flutter-sdk#64]
* flutter 版本 1.9.1 hotfix 6
* 异常设备Android，已知机型:
1.华为畅享7p version: emui 5.1.3 android 7.0 cpu Snapdragon 435
安装时会提示安装失败: 该应用与此设备Cpu不兼容
2.三星 Galaxy J3 Pro SM-j3119
安装时的日志
adb: failed to install /Users/xxx/yyyy/zzz/build/app/outputs/apk/app.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
Error: Failed to install APK again.
Error launching application on TRT AL00.

build.gradle文件设置如下:

android {
    compileSdkVersion 28
    lintOptions {
        disable 'InvalidPackage'
    }
    defaultConfig {
        applicationId "com.xxx.zzzz"
        minSdkVersion 17
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters "arm64-v8a"
        }
    }
    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}
flutter {
    source '../..'
}
dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.3.0-alpha02'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0-alpha02'
    implementation 'com.google.code.gson:gson:2.8.2'
}

推测可能是 该机型无法适配abi: arm64-v8a
望从官方寻求解决方案。

**Comment by loginSin** [comment]
可以将 apk 解压出来，看一下 lib 目录有什么 cpu 架构，需要包含 flutter，app，imlib，sqlite 等 so 文件，可以看一下 arm64-v8a 里面是少了哪个 的架构
或者可以试着将 ndk 降级，比如改为低版本的 v7a 试试 
ndk {
            abiFilters "armeabi-v7a"
        }

**Comment by MaChengtianjiang** [comment]
嗯.就是的,拿了真机 运行了一下看abi就只只能跑armeabi-v7a。
但是所使用的骁龙435 cpu官网却说是支持arm-v8a的.
