### ISSUE TITLE
播放语音卡死，发送语音对方无法接收， 接收语音无法识别消息RC：VsMsg

### ISSUE THREAD

**Issue by yfm-pliny** [rongcloud/rongcloud-im-flutter-sdk#65]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息 1.9.1+hotfix.6
* 异常设备是Android，荣耀9x，Android版本9
* 用的example,换成了自己appkey，录语音发送，播放自己的语音app卡死，控制台报错：Exception: PlatformException(ERR_UNKNOWN, ERR_UNKNOWN, Prepare failed.: status=0x1)。在三星手机上播放自己的语音倒是正常
  在对方接收语音ios显示是空，但是有红点通知，  对方接收语音android显示当前版本不支持查看此消息

文档链接 https://github.com/rongcloud/rongcloud-im-flutter-sdk/tree/dev/doc
文档持续更新中……

**Comment by loginSin** [comment]
是直接使用的本项目中的 example 出现的问题是吗？还是使用 SDK 自己开发的过程出现了该问题？
可否提供一下完整的 logcat 的日志？仅根据上面的描述可以大致分析出貌似是 三星手机录制发送过程中出现了问题，导致发送的语音消息有问题，所以对方收到的消息有问题；三星手机可以播放是因为使用的本地的语音资源
需要详细的 log 来分析具体的问题，否则这边也只能猜

**Comment by yfm-pliny** [comment]
是的，我使用的是你们提供的example, 异常设备是Android，荣耀9x，Android版本9.  我在跟已经上线的原生app发送消息测试。 我发送语音给原生ios会显示空，发送给原生安卓会显示无法识别消息RC：VsMsg ，  我录制语音消息后，播放自己的语音会卡死。 

日志：
2019-12-26 15:31:29.284 17452-17471/com.example.rongcloud_im_plugin_example E/MediaPlayerNative: error (1, -2147483648)
2019-12-26 15:31:29.285 17452-17452/com.example.rongcloud_im_plugin_example E/FlutterSoundPlugin: startPlayer() exception
2019-12-26 15:31:29.307 17452-17486/com.example.rongcloud_im_plugin_example E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Exception: PlatformException(ERR_UNKNOWN, ERR_UNKNOWN, Prepare failed.: status=0x1)
    #0      FlutterSound._startPlayer (package:flutter_sound/flutter_sound.dart:196:7)
    <asynchronous suspension>
    #1      FlutterSound.startPlayer (package:flutter_sound/flutter_sound.dart:201:51)
    <asynchronous suspension>
    #2      MediaUtil.startPlayAudio (package:rongcloud_im_plugin_example/im/util/media_util.dart:93:18)
    #3      _ConversationPageState.didTapMessageItem (package:rongcloud_im_plugin_example/im/pages/conversation_page.dart:290:26)
    #4      _ConversationItemState.__onTapedMesssage (package:rongcloud_im_plugin_example/im/pages/item/conversation_item.dart:117:16)
    #5      _ConversationItemState.buildMessageWidget.<anonymous closure> (package:rongcloud_im_plugin_example/im/pages/item/conversation_item.dart:154:17)
    #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
    #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
    #8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
    #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
    #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
    #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
    #12     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
    #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
    #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
    #15     _rootRunUnary (dart:async/zone.dart:1136:13)
    #16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
    #18     _invoke1 (dart:ui/hooks.dart:263:10)
    #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
2019-12-26 15:31:35.765 17452-17452/com.example.rongcloud_im_plugin_example E/FlutterSoundPlugin: Player is already running. Stop it first.
2019-12-26 15:31:45.653 17452-17452/com.example.rongcloud_im_plugin_example E/MediaPlayerNative: stop called in state 0, mPlayer(0xc7014600)
2019-12-26 15:31:45.653 17452-17452/com.example.rongcloud_im_plugin_example E/MediaPlayerNative: error (-38, 0)
2019-12-26 15:32:15.846 17452-17480/com.example.rongcloud_im_plugin_example E/MediaPlayerNative: error (1, -2147483648)
2019-12-26 15:32:15.846 17452-17452/com.example.rongcloud_im_plugin_example E/FlutterSoundPlugin: startPlayer() exception
2019-12-26 15:32:15.851 17452-17486/com.example.rongcloud_im_plugin_example E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Exception: PlatformException(ERR_UNKNOWN, ERR_UNKNOWN, Prepare failed.: status=0x1)
    #0      FlutterSound._startPlayer (package:flutter_sound/flutter_sound.dart:196:7)
    <asynchronous suspension>
    #1      FlutterSound.startPlayer (package:flutter_sound/flutter_sound.dart:201:51)
    <asynchronous suspension>
    #2      MediaUtil.startPlayAudio (package:rongcloud_im_plugin_example/im/util/media_util.dart:93:18)
    #3      _ConversationPageState.didTapMessageItem (package:rongcloud_im_plugin_example/im/pages/conversation_page.dart:290:26)
    #4      _ConversationItemState.__onTapedMesssage (package:rongcloud_im_plugin_example/im/pages/item/conversation_item.dart:117:16)
    #5      _ConversationItemState.buildMessageWidget.<anonymous closure> (package:rongcloud_im_plugin_example/im/pages/item/conversation_item.dart:154:17)
    #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
    #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
    #8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
    #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
    #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
    #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
    #12     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
    #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
    #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
    #15     _rootRunUnary (dart:async/zone.dart:1136:13)
    #16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
    #18     _invoke1 (dart:ui/hooks.dart:263:10)
    #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
2019-12-26 15:32:15.856 17452-17452/com.example.rongcloud_im_plugin_example E/FlutterSoundPlugin: Player is already running. Stop it first.

**Comment by yfm-pliny** [comment]
对了，已经上线的原生安卓那边发语音消息给我，也会显示：无法识别消息RC：VsMsg

**Comment by loginSin** [comment]
确定使用的语音消息是 RC:VsMsg 吗？那你可能使用的不是我们官方的 SDK，我们官方的 SDK 中语音消息为 RC:HQVCMsg

你可以参考下面连接的第六行
https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/lib/src/voice_message.dart

**Comment by loginSin** [comment]
已经上线的 Android 是用原生的 Android SDK 开发的吗？
原生 SDK 有两种语音消息：
旧版的 RC:VcMsg 语音格式为 wav，新版为 RC:HQVCMsg 语音格式为 aac
因为没有可以录制播放 wav 格式的开源的 Flutter 插件，所以我们 IM Flutter SDK 使用的是新版 RC:HQVCMsg 的语音消息

**Comment by yfm-pliny** [comment]
> 已经上线的Android的是用原生的Android的SDK开发的吗？
> 原生SDK有两种语音消息：
> 旧版的RC：VcMsg语音格式为WAV，新版为RC：HQVCMsg语音格式为AAC
> 因为没有可以录制播放WAV格式的开源的Flutter插件，所以我们IM Flutter SDK使用的是新版RC：HQVCMsg的语音消息

好吧，估计原生Android开发的时候用的旧版sdk。 是去年开发的项目。  目前剩下的问题是，我的荣耀手机播放自己的录音是会奔溃。  在三星手机上是正常的。

**Comment by CNHarrySun** [comment]
你好，请问换成 RC:HQVCMsg 后还有播放录音崩溃这个问题吗？
