### ISSUE TITLE
RongcloudImPlugin.connect 时出错 java.lang.NoSuchFieldException: No field mRegCache in class Lio/rong/imlib/p0;

### ISSUE THREAD

**Issue by wantg** [rongcloud/rongcloud-im-flutter-sdk#66]
RongcloudImPlugin.connect 时出错
调试模式下正常，仅在编译成APK之后运行时会出现

* Flutter 1.12.13+hotfix.5
* Android 华为Honor V8 Android 7.0
* 报错信息详见日志

[log.txt](https://github.com/rongcloud/rongcloud-im-flutter-sdk/files/4005484/log.txt)

**Comment by yfm-pliny** [comment]
同上，之前一直在用的，手贱更新到了flutter 1.12.13之后。 官方的example都运行不起来了。
log:
Couldn't read file LocalFile:
'/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/audio_recorder-1.0.1/android/src/main/ko
tlin/com/jordanalcaraz/audiorecorder/audiorecorder/AudioRecorderPlugin.kt' even though it exists.
Please verify that this file has read permission and try again.

**Comment by wantg** [comment]
> 同上，之前一直在用的，手贱更新到了flutter 1.12.13之后。 官方的example都运行不起来了。
> log:
> Couldn't read file LocalFile:
> '/Applications/flutter/.pub-cache/hosted/pub.flutter-io.cn/audio_recorder-1.0.1/android/src/main/ko
> tlin/com/jordanalcaraz/audiorecorder/audiorecorder/AudioRecorderPlugin.kt' even though it exists.
> Please verify that this file has read permission and try again.

@yfm-pliny 
这个是Flutter的bug，不是融云的问题。
修复方法:
把
```
FLUTTER_HOME/.pub-cache/hosted/pub.dartlang.org/audio_recorder-1.0.1/android/src/main/java/com/jordanalcaraz/audiorecorder
```
目录中的
`audio_recorder` 改名为 `audiorecorder`

**Comment by wantg** [comment]
Duplicate of #68

**Comment by devxnan** [comment]
> RongcloudImPlugin.connect 时出错
> 调试模式下正常，仅在编译成APK之后运行时会出现
> 
> * Flutter 1.12.13+hotfix.5
> * Android 华为Honor V8 Android 7.0
> * 报错信息详见日志
> 
> [log.txt](https://github.com/rongcloud/rongcloud-im-flutter-sdk/files/4005484/log.txt)

老哥你解决了吗？怎么解决的？
