### ISSUE TITLE
聊天页面发送信息时直接卡死。并不报错

### ISSUE THREAD

**Issue by ysyniko** [rongcloud/rongcloud-im-flutter-sdk#67]
本地 Flutter 1.12
* Android 三星
* 发送信息时直接卡死，并不报错，程序提示没有响应。
* 官网的例子也无法运行，一直提示没有响应

**Comment by loginSin** [comment]
请提供一下问题发生前后完整的 log，只有问题的描述没办法准确定位问题

**Comment by loginSin** [comment]
https://github.com/rongcloud/rongcloud-im-flutter-sdk/issues/68
可能的原因跟这个类似，没有找到对应的 so 文件导致的没有连接 im 成功，可以参照该连接的解决方案
