### ISSUE TITLE
聊天列表无法保持滚动状态

### ISSUE THREAD

**Issue by wantg** [rongcloud/rongcloud-im-flutter-sdk#69]
从聊天内容回到聊天列表时，滚动位置丢失。

![Screen-Recording-2020-01-08-at-4 22 58-PM](https://user-images.githubusercontent.com/963880/71962037-94d61380-3233-11ea-88ea-4e15e4ee954d.gif)

**Comment by CNHarrySun** [comment]
这个暂时没有修复，在 feat/1.0.7 分支中会话列表中修复了这个，您可以参考下，后面我们会修复会话列表页面。
