### ISSUE TITLE
发送图片成功 聊天列表里ImageMessage没办法显示图片啊     @override   String conversationDigest() {     return "图片";   }

### ISSUE THREAD

**Issue by zhangyuanze** [rongcloud/rongcloud-im-flutter-sdk#7]
发送图片成功 聊天列表里ImageMessage没办法显示图片啊    

  @override
  String conversationDigest() {
    return "图片";
  }

**Comment by loginSin** [comment]
聊天页面显示图片的逻辑是怎么样的？没有相关代码，没办法定位问题

**Comment by zhangyuanze** [comment]
你好 下面是我发送图片的code   

onSendImageMessage() async {
    var image = await ImagePicker.pickImage(source: ImageSource.gallery);
    ImageMessage imgMessage = new ImageMessage();
    imgMessage.localPath = 'file:/'+image.path;
    Message msg = await RongcloudImPlugin.sendMessage(RCConversationType.Private, privateUserId, imgMessage);
    Provider.of<CartProvider>(context, listen: false).collectReceiveMsg(msg);
  }


发送成功后  返回的这个msg 获取不到适合展示图片相关的合适信息 以下是你的源码哦


import 'rc_status_define.dart';
import 'message_content.dart';
import 'dart:convert' show json;

class ImageMessage extends MessageContent {
  static const String objectName = "RC:ImgMsg";

  String localPath;
  String extra;
  String content;
  String imageUri;

  @override
  void decode(String jsonStr) {
    Map map = json.decode(jsonStr.toString());
    this.localPath = map["localPath"];
    this.content = map["content"];
    this.imageUri = map["imageUri"];
    this.extra = map["extra"];
  }

  @override
  String encode() {
    Map map = {"localPath":this.localPath,"extra":this.extra};
    return json.encode(map);
  }

  @override
  String conversationDigest() {
    return "图片";
  }

  @override
  String getObjectName() {
    return objectName;
  }
}


这个是获取到的localPath
file:///data/user/0/com.example.flutter_project/files/CFyR9nT2N9KSCPlUrR-91Q/image/local/367.jpg


import 'message_content.dart';

class Message extends Object {
  int conversationType;//会话类型 参见 RCConversationType
  String targetId;//会话 id
  int messageId;//messageId ，本地数据库的自增 id
  int messageDirection;//消息方向 参见 RCMessageDirection
  String senderUserId;//发送者 id
  int receivedStatus;//消息接收状态 参见 RCReceivedStatus
  int sentStatus;//消息发送状态 参见 RCSentStatus
  int sentTime;//发送时间，unix 时间戳，单位毫秒
  String objectName;//消息 objName
  MessageContent content;//消息内容
  String messageUId;//消息 UID，全网唯一 Id
  
  //如果 content 为 null ，说明消息内容本身未被 flutter 层正确解析，则消息内容会保存到该 map 中
  Map originContentMap;
}
