### ISSUE TITLE
请问自定义消息如何发送于接收？

### ISSUE THREAD

**Issue by goodsiwen** [rongcloud/rongcloud-im-flutter-sdk#70]
请问自定义消息如何发送于接收？

**Comment by CNHarrySun** [comment]
非常抱歉，这个暂时没有添加注册自定义消息的入口，目前仅支持基础的消息类型，后面会尽快排期添加入口。

**Comment by CNHarrySun** [comment]
可以先参考 https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/doc/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B6%88%E6%81%AF.md 实现
