### ISSUE TITLE
Gradle 构建错误

### ISSUE THREAD

**Issue by shs8023you** [rongcloud/rongcloud-im-flutter-sdk#72]
下载demo运行提示构建错误 

C:\environment\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_sound-1.9.0\android\src\main\java\com\dooboolab\fluttersound\FlutterSoundPlugin.java:12: ����: �Ҳ�������
import android.support.v4.app.ActivityCompat;
                             ^
  ����:   �� ActivityCompat
  λ��: ����� android.support.v4.app
C:\environment\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_sound-1.9.0\android\src\main\java\com\dooboolab\fluttersound\FlutterSoundPlugin.java:44: ����: �Ҳ�������
        ActivityCompat.requestPermissions(activity, new String[]{Manifest.permission.RECORD_AUDIO,}, 0);
        ^
  ����:   ��� ActivityCompat
  λ��: �� sdkCompat
2 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_sound:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin camera...
Running Gradle task 'assembleAarRelease'...
√ Built build\app\outputs\repo.
Building plugin flutter_audio_recorder...
Running Gradle task 'assembleAarRelease'...
√ Built build\app\outputs\repo.
Building plugin flutter_local_notifications...
Running Gradle task 'assembleAarRelease'...
√ Built build\app\outputs\repo.
Building plugin flutter_plugin_android_lifecycle...
Running Gradle task 'assembleAarRelease'...
√ Built build\app\outputs\repo.
Building plugin flutter_sound...
Running Gradle task 'assembleAarRelease'...
> Task :assembleAarRelease UP-TO-DATE
> Task :preBuild UP-TO-DATE
> Task :preReleaseBuild UP-TO-DATE
> Task :compileReleaseAidl NO-SOURCE
> Task :compileReleaseRenderscript NO-SOURCE
> Task :checkReleaseManifest UP-TO-DATE
> Task :generateReleaseBuildConfig UP-TO-DATE
> Task :generateReleaseResValues UP-TO-DATE
> Task :generateReleaseResources UP-TO-DATE
> Task :packageReleaseResources UP-TO-DATE
> Task :processReleaseManifest UP-TO-DATE
> Task :generateReleaseRFile UP-TO-DATE
> Task :prepareLintJar UP-TO-DATE
> Task :generateReleaseSources UP-TO-DATE
> Task :javaPreCompileRelease UP-TO-DATE

> Task :compileReleaseJavaWithJavac FAILED

> Task :mergeReleaseConsumerProguardFiles UP-TO-DATE
> Task :mergeReleaseShaders UP-TO-DATE
> Task :compileReleaseShaders UP-TO-DATE
> Task :generateReleaseAssets UP-TO-DATE
> Task :packageReleaseAssets UP-TO-DATE
> Task :packageReleaseRenderscript NO-SOURCE
> Task :prepareLintJarForPublish UP-TO-DATE
> Task :processReleaseJavaRes NO-SOURCE
> Task :mergeReleaseJniLibFolders UP-TO-DATE
> Task :transformNativeLibsWithMergeJniLibsForRelease UP-TO-DATE
> Task :transformNativeLibsWithStripDebugSymbolForRelease UP-TO-DATE
> Task :transformNativeLibsWithSyncJniLibsForRelease UP-TO-DATE
18 actionable tasks: 1 executed, 17 up-to-date

C:\environment\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_sound-1.9.0\android\src\main\java\com\dooboolab\fluttersound\FlutterSoundPlugin.java:12: 错误: 程序包android.support.v4.app不存在
import android.support.v4.app.ActivityCompat;
                             ^
C:\environment\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_sound-1.9.0\android\src\main\java\com\dooboolab\fluttersound\FlutterSoundPlugin.java:44: 错误: 找不到符号
        ActivityCompat.requestPermissions(activity, new String[]{Manifest.permission.RECORD_AUDIO,}, 0);
        ^
  符号:   变量 ActivityCompat
  位置: 类 sdkCompat
2 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

Finished with error: The plugin flutter_sound could not be built due to the issue above.

**Comment by CNHarrySun** [comment]
你好，进入到 C:\environment\flutter.pub-cache\hosted\pub.dartlang.org\flutter_sound-1.9.0\android\src\main\java\com\dooboolab\fluttersound\FlutterSoundPlugin.java，然后将 的 import android.support.v4.app.ActivityCompat; 修改为 import androidx.core.app.ActivityCompat; 试下，修改前做好备份。
