### ISSUE TITLE
运行demo到Android手机上直接闪退

### ISSUE THREAD

**Issue by love-bk** [rongcloud/rongcloud-im-flutter-sdk#75]

**Comment by yfm-pliny** [comment]
我这里也是。
最新版flutter  ，在android studio 上运行报错
错误: 找不到符号
符号:   类 ActivityCompat
位置: 程序包 android.support.v4.app

**Comment by fangmd** [comment]
是 Androidx 的问题吧

**Comment by CNHarrySun** [comment]
在 AndroidX 环境上此类已经做包的迁移，请将类的包换成 AndroidX 下正确的包名即可。

**Comment by fangmd** [comment]
我这里运行报这个错 (git clone 下后用 AS 运行 example/main.dart)

环境:

```
Flutter (Channel stable, v1.12.13+hotfix.8,
```

```
/Users/double/.pub-cache/hosted/pub.flutter-io.cn/flutter_sound-1.9.0/android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java:12: error: cannot find symbol
import android.support.v4.app.ActivityCompat;
                             ^
  symbol:   class ActivityCompat
  location: package android.support.v4.app
/Users/double/.pub-cache/hosted/pub.flutter-io.cn/flutter_sound-1.9.0/android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java:44: error: cannot find symbol
        ActivityCompat.requestPermissions(activity, new String[]{Manifest.permission.RECORD_AUDIO,}, 0);
        ^
  symbol:   variable ActivityCompat
  location: class sdkCompat
2 errors
```

**Comment by CNHarrySun** [comment]
您进入到 /Users/double/.pub-cache/hosted/pub.flutter-io.cn/flutter_sound-1.9.0/android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java

将 import android.support.v4.app.ActivityCompat; 修改成 import androidx.core.app.ActivityCompat; 试下，修改前最好将该文件复制一份。

**Comment by fangmd** [comment]
> 您进入到 /Users/double/.pub-cache/hosted/pub.flutter-io.cn/flutter_sound-1.9.0/android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java
> 
> 将 import android.support.v4.app.ActivityCompat; 修改成 import androidx.core.app.ActivityCompat; 试下，修改前最好将该文件复制一份。

了解了，之前吧 flutter_sound 去掉后确实能运行了，但是打开后没有东西（像闪退）。

对比了下新建的空工程: example 里面的 MainActivity 的写法和官方最新的有点差异。

下面的是官方最新 (v1.12.13+hotfix.8) 的写法：

```
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
```

**Comment by CNHarrySun** [comment]
删除之后重新执行 flutter pub get，然后再运行看下是否正常运行。
