### ISSUE TITLE
方法 sendReadReceiptMessage 无效

### ISSUE THREAD

**Issue by psychokiller666** [rongcloud/rongcloud-im-flutter-sdk#78]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
Flutter 1.12.13+hotifx.5
* 异常设备是 iOS 还是 Android，列出具体机型和系统
模拟器 ios 13.1，android 27
* 所调用的是什么 API 或者说是什么功能
sendReadReceiptMessage 发送已读回执
* 完整的报错信息或者问题描述
返回code 0成功，但是会话列表，Conversation里面的，unreadMessageCount 属性没变
* 提供问题发生时必要的日志，并以 txt 形式上传

文档链接 https://github.com/rongcloud/rongcloud-im-flutter-sdk/tree/dev/doc
文档持续更新中……

**Comment by CNHarrySun** [comment]
您需要在收到已读回执的时候重新获取会话列表更新页面：
RongcloudImPlugin.onReceiveReadReceipt = (Map map) {
  // 接收已读回执，需要通知会话列表重新拉取数据并刷新
};
