### ISSUE TITLE
demo 中 flutter sdk 运行版本是多少，为什么我换了好几个版本都报错

### ISSUE THREAD

**Issue by hlj2722** [rongcloud/rongcloud-im-flutter-sdk#79]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
* 异常设备是 iOS 还是 Android，列出具体机型和系统
* 所调用的是什么 API 或者说是什么功能
* 完整的报错信息或者问题描述
* 提供问题发生时必要的日志，并以 txt 形式上传

文档链接 https://github.com/rongcloud/rongcloud-im-flutter-sdk/tree/dev/doc
文档持续更新中……

**Comment by CNHarrySun** [comment]
您好，您先执行 flutter upgrade 更新一下 flutter 的版本。
