### ISSUE TITLE
在iOS环境就不起来

### ISSUE THREAD

**Issue by zhangyuanze** [rongcloud/rongcloud-im-flutter-sdk#8]
用了你这个sdk之后 我的app在iOS环境就不起来了  
build的时候 一直Running pod install... 
请把flutter iOS环境集成你这个包的教程细化一些

**Comment by loginSin** [comment]
可能是 pod 安装 im  SDK 的 问题，你可以手动在 iOS 项目目录执行  pod update 命令，手动安装 pod 依赖，然后再通过 flutter 命令继续后面的操作

**Comment by zhangyuanze** [comment]
好的 谢谢 我看了一下 pod update 之前是没有那个imsdk，  pod update 之后有那个sdk就OK了
