### ISSUE TITLE
需要导入融云的Android和ios的sdk吗？第一次做即时通讯所以不是很懂，求大佬指教一下，谢谢了

### ISSUE THREAD

**Issue by huandeihuanshi** [rongcloud/rongcloud-im-flutter-sdk#81]

**Comment by CNHarrySun** [comment]
不需要导入，Flutter SDK 中分别植入了 Android 和 iOS 的 SDK。
Android 版本在 android/build.gradle 中查看版本
iOS 是使用的你本地 pod 中的最新版本
