### ISSUE TITLE
自定义消息的MessageTag无效

### ISSUE THREAD

**Issue by leielyq** [rongcloud/rongcloud-im-flutter-sdk#82]
@MessageTag(value = "custom_msg", flag = MessageTag.NONE)  
自定义消息Tag设置为以上样式，使用Flutter的onGetHistoryMessages接口，依然可以获取。
随后发现，貌似只有导入imkit包才可以使用MessageTag，自定义的消息，希望可以解决一下这个问题

**Comment by leielyq** [comment]
有人吗

**Comment by CNHarrySun** [comment]
非常感谢您的建议，我们会尽快排期完善此功能。

**Comment by leielyq** [comment]
OK
