### ISSUE TITLE
Flutter 语音消息的问题

### ISSUE THREAD

**Issue by leielyq** [rongcloud/rongcloud-im-flutter-sdk#83]
flutter  SDK 中 语音消息类型是  objectName = "RC:HQVCMsg";
使用该方法发送 RongcloudImPlugin.sendMessage(
        conversationType, privateUserId, content);

在原生  Android端无法接收  Android  采用imkit开发的

**Comment by CNHarrySun** [comment]
这个测试了是可以互通的，需要确保测试时 AppKey 是同一个。
看下原生 Android 端的接收消息监听中是否收到消息以及 flutter 层发送消息时控制台的日志。

**Comment by leielyq** [comment]
> 这个测试了是可以互通的，需要确保测试时 AppKey 是同一个。
> 看下原生 Android 端的接收消息监听中是否收到消息以及 flutter 层发送消息时控制台的日志。

对了  刚刚测试确实可以了，谢谢，还有一个问题，请问Android端发送的语音消息类型是RC:VcMSg，flutter SDK  打印的是  I/flutter (11561): RC:VcMsg:该消息不能被解析!消息内容被保存在 Conversation.originContentMap 中

**Comment by leielyq** [comment]
但是  如果 flutter 项目运行在Android端的话  originContentMap 里面只有 duration ,isBurnAfterRead,burnDuration三个值，
如果 flutter 项目运行在iOS端的话  originContentMap 里面还有一段加密的文本

**Comment by leielyq** [comment]
有没有可能是Flutter 依赖的SDK 版本问题 ，Android原生已经升级到2.10.4了，但是Flutter SDK版本是2.9

**Comment by zoulu123** [comment]
用 kit 的话请在 initSDk 时调用RongIM.getInstance().setVoiceMessageType(RongIM.VoiceMessageType.HighQuality);
lib 的话您要自行构造 HQVoiceMessage 用于发送

**Comment by leielyq** [comment]
ok
