### ISSUE TITLE
发送文本消息失败

### ISSUE THREAD

**Issue by mengsiyitiaojie** [rongcloud/rongcloud-im-flutter-sdk#84]
sendMessage 自定义消息没有加注解信息。

**Comment by CNHarrySun** [comment]
您好，自定义消息参考这个：https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/doc/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B6%88%E6%81%AF.md
