### ISSUE TITLE
安卓打包后不能连接融云

### ISSUE THREAD

**Issue by mengsiyitiaojie** [rongcloud/rongcloud-im-flutter-sdk#85]
安卓打包后不能连接融云

**Comment by CNHarrySun** [comment]
您好，连接的报错信息是什么？
您那检查下 AppKey、token 是否正确。

**Comment by kossfun** [comment]
flutter build apk --target-platform android-arm --split-per-abi

java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/user/0/com.demo.rc_flutter/app_lib/libRongIMLib.so"

打包后运行报这个

**Comment by zoulu123** [comment]
请问您有做如下配置吗？
ndk {
            abiFilters "armeabi-v7a"
 }
您配的是啥这部分的配置？

**Comment by eyesoffish** [comment]
我也遇到了,flutter build apk, 然后连接融云没有反应,也不报错try catch 也不会走

**Comment by eyesoffish** [comment]
debug模式下是正常的.

**Comment by fishofeyes** [comment]
Android加上这个配置解决了:
```
android {
    ...
    buildTypes {
        release {
            ...
            shrinkResources false
            minifyEnabled false
        }
    }
    ...
}
```

**Comment by AcmeField** [comment]
> Android加上这个配置解决了:
> 
> ```
> android {
>     ...
>     buildTypes {
>         release {
>             ...
>             shrinkResources false
>             minifyEnabled false
>         }
>     }
>     ...
> }
> ```
谢谢大哥解决了我的问题
