### ISSUE TITLE
发送图片的时候我想携带用户信息，就携带不过去了，无论是在会话列表或者消息历史里面都找不到用户信息，提示为null

### ISSUE THREAD

**Issue by xiaojiedeVX** [rongcloud/rongcloud-im-flutter-sdk#86]

**Comment by CNHarrySun** [comment]
您好，请问是如何携带的用户信息？

可以参考文本消息携带用户信息来写：https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/doc/%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF%E6%90%BA%E5%B8%A6%E7%94%A8%E6%88%B7%E4%BF%A1%E6%81%AF.md

在发送消息前将想携带的用户信息赋值给 message 的 sendUserInfo。

**Comment by xiaojiedeVX** [comment]
文本确实是可以的，但是图片的时候就带不了用户信息


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"HarrySun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 下午2:48
收件人:&nbsp;"rongcloud/rongcloud-im-flutter-sdk"<rongcloud-im-flutter-sdk@noreply.github.com&gt;;
抄送:&nbsp;"1040154247"<1040154247@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rongcloud/rongcloud-im-flutter-sdk] 发送图片的时候我想携带用户信息，就携带不过去了，无论是在会话列表或者消息历史里面都找不到用户信息，提示为null (#86)





 
您好，请问是如何携带的用户信息？
 
可以参考文本消息携带用户信息来写：https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/doc/%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF%E6%90%BA%E5%B8%A6%E7%94%A8%E6%88%B7%E4%BF%A1%E6%81%AF.md
 
在发送消息前将想携带的用户信息赋值给 message 的 sendUserInfo。

**Comment by CNHarrySun** [comment]
确实存在这个问题，下个版本会进行修复。

**Comment by CNHarrySun** [comment]
您好，这个问题已经修复并上线，版本号 1.1.1；感谢您的反馈。
