### ISSUE TITLE
web版应该不能用吧?

### ISSUE THREAD

**Issue by smallseven1213** [rongcloud/rongcloud-im-flutter-sdk#87]
在FlutterPub 1.1.0的tag中发现有web tag
但实际上调用与看了代码后
目前web应该是无法使用对吧?
请问未来会提供web版本吗?

**Comment by CNHarrySun** [comment]
您好，代码中暂时没有 web 相关的接口。
未来是否提供 web 版本需要内部讨论才能决定。
