### ISSUE TITLE
Demo 发送消息

### ISSUE THREAD

**Issue by SSSZhaoShi** [rongcloud/rongcloud-im-flutter-sdk#88]
最新 Demo，发送消息输入框不能显示多行，先发送一张图片，在发送一条文本，页面会闪屏。

**Comment by zoulu123** [comment]
1.输入框的问题，你可以尝试自己做下优化，我们后续会对这个效果进行优化
2.闪屏这个是已知问题，我们也会做出优化
（以上两个问题都为 app 层的问题,您也尝试优化下）
