### ISSUE TITLE
远程推送的问题

### ISSUE THREAD

**Issue by leielyq** [rongcloud/rongcloud-im-flutter-sdk#89]
iOS版可以接收到消息通知。
但是安卓接入的第三方不行。我通过小米后台可以正常推送的。

**Comment by leielyq** [comment]
而且官网后台Android推送连调试的地方都没，iOS的配置就可以直接调试还能告诉我对应的错误

**Comment by zoulu123** [comment]
你尝试下在你的 android 目录下引用初始化下推送的配置
PushConfig config = new PushConfig
                .Builder()
                .enableHWPush(true)
                .enableMiPush("", "")
                .enableMeiZuPush("", "")
                .enableVivoPush(true)
                .enableFCM(true)
                .build();
        RongPushClient.setPushConfig(config);

**Comment by leielyq** [comment]
ok了，是原生和flutter版的后台配置高混淆了，我自己的问题，不好意思

**Comment by w4mxl** [comment]
> ok了，是原生和flutter版的后台配置高混淆了，我自己的问题，不好意思

遇到同样的问题了，请问下你那边后来是怎么配置解决的呢？
