### ISSUE TITLE
消息撤回的问题

### ISSUE THREAD

**Issue by leielyq** [rongcloud/rongcloud-im-flutter-sdk#90]
我看到更新log里面有提到撤回，但是没找到接口。求帮助。
目前一直在做flutter方面，希望能加个微信

**Comment by CNHarrySun** [comment]
您好，您可以参考“消息撤回”的这个文档：https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/feat/1.1.1/doc/%E6%92%A4%E5%9B%9E%E6%B6%88%E6%81%AF.md

或者参考下 [conversation_page.dart](https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/example/lib/im/pages/conversation_page.dart) 中的实现

**Comment by leielyq** [comment]
好的
