### ISSUE TITLE
拉取下来代码之后，运行example内的Android报错file_picker的问题

### ISSUE THREAD

**Issue by JamesBai1** [rongcloud/rongcloud-im-flutter-sdk#92]
为了快速解决问题，在寻求帮助的时候，请提供以下信息，方便我们快速定位问题
* 本地 Flutter 版本信息
答：Flutter 1.16.4-pre.22 ; Tools Dart 2.8.0
* 异常设备是 iOS 还是 Android，列出具体机型和系统
答：window7下使用Android studio 创建的虚拟机,Android8.1 CPU x86
* 所调用的是什么 API 或者说是什么功能
答：运行example
* 完整的报错信息或者问题描述
Exception: The plugin file_picker could not be built due to the issue above,
* 提供问题发生时必要的日志，并以 txt 形式上传
答：如下为详细日志：

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\flutter_sound-1.9.0\android\src\main\java\com\dooboolab\fluttersound\FlutterSoundPlugin.java:12: ����: �Ҳ�������
import android.support.v4.app.ActivityCompat;
                             ^
  ����:   �� ActivityCompat
  λ��: ����� android.support.v4.app
C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\flutter_sound-1.9.0\android\src\main\java\com\dooboolab\fluttersound\FlutterSoundPlugin.java:44: ����: �Ҳ�������
        ActivityCompat.requestPermissions(activity, new String[]{Manifest.permission.RECORD_AUDIO,}, 0);
        ^
  ����:   ��� ActivityCompat
  λ��: �� sdkCompat
2 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_sound:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin camera...
Running Gradle task 'assembleAarRelease'...
√ Built build\app\outputs\repo.
Building plugin file_picker...
Running Gradle task 'assembleAarRelease'...
> Task :assembleAarRelease UP-TO-DATE
> Task :preBuild UP-TO-DATE
> Task :preReleaseBuild UP-TO-DATE
> Task :compileReleaseAidl NO-SOURCE
> Task :compileReleaseRenderscript UP-TO-DATE
> Task :checkReleaseManifest UP-TO-DATE
> Task :generateReleaseBuildConfig UP-TO-DATE
> Task :generateReleaseResValues UP-TO-DATE
> Task :generateReleaseResources UP-TO-DATE
> Task :packageReleaseResources UP-TO-DATE
> Task :processReleaseManifest UP-TO-DATE
> Task :generateReleaseRFile UP-TO-DATE
> Task :prepareLintJar UP-TO-DATE
> Task :generateReleaseSources UP-TO-DATE
> Task :javaPreCompileRelease UP-TO-DATE

> Task :compileReleaseJavaWithJavac FAILED

> Task :mergeReleaseConsumerProguardFiles UP-TO-DATE
> Task :mergeReleaseShaders UP-TO-DATE
> Task :compileReleaseShaders UP-TO-DATE
> Task :generateReleaseAssets UP-TO-DATE
> Task :packageReleaseAssets UP-TO-DATE
> Task :packageReleaseRenderscript NO-SOURCE
> Task :processReleaseJavaRes NO-SOURCE
> Task :compileReleaseNdk NO-SOURCE
> Task :mergeReleaseJniLibFolders UP-TO-DATE
> Task :transformNativeLibsWithMergeJniLibsForRelease UP-TO-DATE
> Task :transformNativeLibsWithSyncJniLibsForRelease UP-TO-DATE

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings
17 actionable tasks: 1 executed, 16 up-to-date

C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\file_picker-1.6.2\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:10: 错误: 找不到符号
import androidx.lifecycle.DefaultLifecycleObserver;
                         ^
  符号:   类 DefaultLifecycleObserver
  位置: 程序包 androidx.lifecycle
C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\file_picker-1.6.2\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:20: 错误: 找不到符号
import io.flutter.embedding.engine.plugins.lifecycle.FlutterLifecycleAdapter;
                                                    ^
  符号:   类 FlutterLifecycleAdapter
  位置: 程序包 io.flutter.embedding.engine.plugins.lifecycle
C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\file_picker-1.6.2\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:36: 错误: 找不到符号
            implements Application.ActivityLifecycleCallbacks, DefaultLifecycleObserver {
                                                               ^
  符号:   类 DefaultLifecycleObserver
  位置: 类 FilePickerPlugin
C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\file_picker-1.6.2\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:43: 错误: 方法不会覆盖或实现超类型的方法
        @Override
        ^
C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\file_picker-1.6.2\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:47: 错误: 方法不会覆盖或实现超类型的方法
        @Override
        ^
C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\file_picker-1.6.2\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:51: 错误: 方法不会覆盖或实现超类型的方法
        @Override
        ^
C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\file_picker-1.6.2\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:55: 错误: 方法不会覆盖或实现超类型的方法
        @Override
        ^
C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\file_picker-1.6.2\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:59: 错误: 方法不会覆盖或实现超类型的方法
        @Override
        ^
C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\file_picker-1.6.2\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:64: 错误: 方法不会覆盖或实现超类型的方法
        @Override
        ^
C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\file_picker-1.6.2\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:251: 错误: 找不到符号
            this.lifecycle = FlutterLifecycleAdapter.getActivityLifecycle(activityBinding);
                             ^
  符号:   变量 FlutterLifecycleAdapter
  位置: 类 FilePickerPlugin
C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\file_picker-1.6.2\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:252: 错误: 不兼容的类型: FilePickerPlugin.LifeCycleObserver无法转换为LifecycleObserver
            this.lifecycle.addObserver(this.observer);
                                           ^
C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\file_picker-1.6.2\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerPlugin.java:260: 错误: 不兼容的类型: FilePickerPlugin.LifeCycleObserver无法转换为LifecycleObserver
        this.lifecycle.removeObserver(this.observer);
                                          ^
注: C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\pub.flutter-io.cn\file_picker-1.6.2\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerDelegate.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些消息已经过简化; 请使用 -Xdiags:verbose 重新编译以获得完整输出
12 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Exception: The plugin file_picker could not be built due to the issue above.

**Comment by CNHarrySun** [comment]
这边可能是您 Android 部分环境不对称导致的引用包找不到的问题，请您按照提示的路径找不到该类，将 v4 包的引用手动改为 androidx 包的路径
