### ISSUE TITLE
撤回本地语音消息失败

### ISSUE THREAD

**Issue by leielyq** [rongcloud/rongcloud-im-flutter-sdk#93]
[https://tva1.sinaimg.cn/large/00831rSTly1gdogiiv0ylj30my0g5ac2.jpg](url)

语音消息是发送接口返回的，没有任何处理，直接调用撤回接口。

**Comment by CNHarrySun** [comment]
您好，25101 是撤回消息参数无效，您是如何调用撤回的接口的？

/*!
    撤回消息参数无效。请确认撤回消息参数是否正确的填写。
     */
    RC_RECALLMESSAGE_PARAMETER_INVALID = 25101,

**Comment by leielyq** [comment]
你好，我通过 id 拿到完整的message  然后调用就可以了

**Comment by leielyq** [comment]
但是  如果是sendMessage接口  不是也会回调一个message对象吗？撤销这个对象就会失败

**Comment by CNHarrySun** [comment]
sendMessage 返回的消息只是加入到本地数据库的消息，没有 messageUId；
所以你需要在消息发送成功后替换数据源中对应的消息。
![image](https://user-images.githubusercontent.com/16249166/79304420-ddccf080-7f23-11ea-9811-4a077e29e86f.png)

**Comment by leielyq** [comment]
好的
