### ISSUE TITLE
[bug]有时会出现闪退问题

### ISSUE THREAD

**Issue by leielyq** [rongcloud/rongcloud-im-flutter-sdk#94]
https://tva1.sinaimg.cn/large/007S8ZIlly1gds3vb2carj30wi0j6juc.jpg

但是这个问题我不确定是我的代码吗

**Comment by CNHarrySun** [comment]
请问还有更多的堆栈信息吗？或者有复现步骤吗。
图中这些看不出来是什么问题导致的。
