### ISSUE TITLE
运行Demo报错

### ISSUE THREAD

**Issue by mengsiyitiaojie** [rongcloud/rongcloud-im-flutter-sdk#95]
fluttersdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_sound-1.9.0/android/src/main/java/com/dooboolab/fluttersound/FlutterSoundPlugin.java:44: 错误: 找不到符号
        ActivityCompat.requestPermissions(activity, new String[]{Manifest.permission.RECORD_AUDIO,}, 0);
        ^
  符号:   变量 ActivityCompat
  位置: 类 sdkCompat
2 个错误

ProcessException: Permission denied

**Comment by CNHarrySun** [comment]
可能是您 Android 部分环境不对称导致的引用包找不到的问题，请您按照提示的路径找不到该类，将 v4 包的引用手动改为 androidx 包的路径
