### ISSUE TITLE
请问有推送功能吗

### ISSUE THREAD

**Issue by mengsiyitiaojie** [rongcloud/rongcloud-im-flutter-sdk#96]
请问有推送功能吗 融云的远程推送

**Comment by CNHarrySun** [comment]
IM Flutter Plugin 核心是 iOS/Android 的原生 SDK，所以远程推送与原生 SDK 的方式一致

[iOS 远程推送文档](https://docs.rongcloud.cn/v3/views/im/noui/guide/private/notify/push/ios.html)

[Android 远程推送文档](https://docs.rongcloud.cn/v3/views/im/noui/guide/private/notify/push/rong.html)
