### ISSUE TITLE
demo运行出错

### ISSUE THREAD

**Issue by ToZhanChi** [rongcloud/rongcloud-im-flutter-sdk#97]
Launching lib\main.dart on kiw al10 in debug mode...
Running Gradle task 'assembleDebug'...
ע: D:\BC\service\flutter_stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\camera-0.5.7+4\android\src\main\java\io\flutter\plugins\camera\CameraPlugin.javaʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: D:\BC\service\flutter_stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\file_picker-1.6.3+1\android\src\main\java\com\mr\flutter\plugin\filepicker\FilePickerDelegate.javaʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
D:\BC\service\flutter_stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\flutter_sound-1.9.0\android\src\main\java\com\dooboolab\fluttersound\FlutterSoundPlugin.java:12: ����: �Ҳ�������
import android.support.v4.app.ActivityCompat;
                             ^
  ����:   �� ActivityCompat
  λ��: ����� android.support.v4.app
D:\BC\service\flutter_stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\flutter_sound-1.9.0\android\src\main\java\com\dooboolab\fluttersound\FlutterSoundPlugin.java:44: ����: �Ҳ�������
        ActivityCompat.requestPermissions(activity, new String[]{Manifest.permission.RECORD_AUDIO,}, 0);
        ^
  ����:   ��� ActivityCompat
  λ��: �� sdkCompat
2 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_sound:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 50s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
✏️  Creating `android\settings_aar.gradle`...
[!] Flutter tried to create the file `android\settings_aar.gradle`, but failed.
To manually update `settings.gradle`, follow these steps:

    1. Copy `settings.gradle` as `settings_aar.gradle`
    2. Remove the following code from `settings_aar.gradle`:

            def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

            def plugins = new Properties()
            def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
            if (pluginsFile.exists()) {
                pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
            }

            plugins.each { name, path ->
                def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
                include ":$name"
                project(":$name").projectDir = pluginDirectory
            }

Finished with error: Please create the file and run this command again.

**Comment by ToZhanChi** [comment]
目前定位到是例子引入 flutter_sound: ^1.4.2这个插件问题

**Comment by CNHarrySun** [comment]
您好，已经在工单回复。

解决如下：
这个是 flutter_sound 库自带的问题，因为我们 example android 端用的是 androidx 环境，可是下载的库中那个类依然依赖的的 support 包，所以导致的问题，如果升级库的版本依然未修复此问题，请您根据提示的路径找到相应类 FlutterSoundPlugin.java
D:\BC\service\flutter_stable\flutter\.pub-cache\hosted\pub.flutter-io.cn\flutter_sound-1.9.0\android\src\main\java\com\dooboolab\fluttersound\FlutterSoundPlugin.java:

将 import android.support.v4.app.ActivityCompat; 替换成 androidx 的包路径 androidx.core.app.ActivityCompat; 即可
