### ISSUE TITLE
请问有没有人成功的吧Demo跑通过？

### ISSUE THREAD

**Issue by ToZhanChi** [rongcloud/rongcloud-im-flutter-sdk#98]
我3个月来从来没有跑通Demo

**Comment by CNHarrySun** [comment]
您好，问题已于 [issues97](https://github.com/rongcloud/rongcloud-im-flutter-sdk/issues/97) 中处理

**Comment by fishofeyes** [comment]
跑起来了。iOS和安卓都可以

**Comment by IOCloudFly** [comment]
> 跑起来了。iOS和安卓都可以

我想请教一下，我只跑了安卓版本，我想问下如何跑ios项目。

**Comment by CNHarrySun** [comment]
> > 跑起来了。iOS和安卓都可以
> 
> 我想请教一下，我只跑了安卓版本，我想问下如何跑ios项目。

你好，进入到 example 目录，执行 flutter run 即可，需要确保本地 iOS 环境和 pod 正常。
参考链接：https://github.com/rongcloud/rongcloud-im-flutter-sdk/blob/master/doc/iOS%20%E8%BF%90%E8%A1%8C%E6%AD%A5%E9%AA%A4%E8%AF%A6%E8%A7%A3.md
